const test=require('node:test'),assert=require('node:assert/strict'),F=require('../core.js');
// The store is loaded after the domain in the ExtendScript bundle; mirror that order here.
global.FormalStep1=F;global.FormalStore=require('../store.js');
function edit(b,p){return Object.assign({reading:'にほんていえん',enabled:true,readingConfirmed:true,placementMode:'auto',style:b.annotation.style,offset:b.annotation.offset},p||{});}
function obs(status='complete'){return{status,metrics:{left:0,top:100,width:80,baseSize:20,fontName:'Test'}};}
test('store round trip preserves foreign note',()=>{let b=F.create('日本庭園'),n=FormalStore.write('foreign\n',b);assert.deepEqual(FormalStore.read(n),b);assert.ok(n.startsWith('foreign\n'));});
test('store rejects version and duplicate envelopes',()=>{let b=F.create('日本庭園'),n=FormalStore.write('',b);assert.throws(()=>FormalStore.read(n.replace('v2-formal-step1:v1','v2-formal-step1:v9')));assert.throws(()=>FormalStore.read(n+n));});
test('anchor ambiguous and missing remain unresolved',()=>{let b=F.create('日本'),a=b.annotation.anchor;a.baseText='日本';a.beforeContext='';a.afterContext='';assert.equal(F.resolve('日本日本',b.textSnapshot,b.annotation).status,'unresolved');assert.equal(F.resolve('別文',b.textSnapshot,b.annotation).status,'unresolved');});
test('desired zero differs from unresolved and failed',()=>{let b=F.create('日本');b.annotation=Object.assign(b.annotation,edit(b));assert.equal(F.plan(b,b.textSnapshot,obs('failed')).status,'failed');assert.equal(F.plan(b,b.textSnapshot,obs('unresolved')).status,'unresolved');b.annotation.enabled=false;assert.deepEqual(F.plan(b,b.textSnapshot,obs('failed')),{status:'complete',desired:[]});});
test('three reconciles remain one and suppression keeps semantics',()=>{let state={text:'日本',note:'foreign'},count=0,p={snapshot:()=>({text:state.text,note:state.note}),inspect:()=>count?[{}]:[],observe:()=>obs(),store:(e,b)=>{state.note=FormalStore.write(e,b);return state.note;},reconcile:()=>{count=1;}};let c={snapshot:p.snapshot(),bundle:F.create(state.text)};for(let i=0;i<3;i++){let r=F.apply(p,c,edit(c.bundle));assert.equal(r.bundle.renderStatus,'complete');c={snapshot:p.snapshot(),bundle:FormalStore.read(state.note)};}let r=F.apply(p,c,edit(c.bundle,{enabled:false}));assert.equal(r.bundle.renderStatus,'complete');assert.equal(count,1);assert.equal(FormalStore.read(state.note).annotation.enabled,false);});
test('render failure stores stage and exception',()=>{let b=F.create('日本'),state={text:'日本',note:''},p={snapshot:()=>({text:state.text,note:state.note}),inspect:()=>[],observe:()=>obs(),store:(e,x)=>{state.note=FormalStore.write(e,x);return state.note;},diagnostics:()=>['render:create:start'],reconcile:()=>{throw Error('property is read only')}};let r=F.apply(p,{snapshot:p.snapshot(),bundle:b},edit(b));assert.equal(r.bundle.renderStatus,'failed');assert.ok(r.bundle.annotation.reviewReasons.join('|').includes('property is read only'));});
test('adapter point text avoids threaded properties and detects output collision',()=>{const fs=require('fs'),vm=require('vm'),src=fs.readFileSync(require('path').join(__dirname,'..','adapter.jsx'),'utf8'),doc={typename:'Document',textFrames:[]},layer={typename:'Layer',parent:doc},chars='日本'.split('').map((x,i)=>({contents:x,start:i,end:i+1,characterAttributes:{size:20,textFont:{name:'Test'}}})),source={typename:'TextFrame',parent:doc,layer,note:'',contents:'日本',kind:'point',orientation:'horizontal',left:0,top:100,width:80,textRange:{start:0,end:2,characters:chars,lines:[{start:0,end:2,contents:'日本'}]}};Object.defineProperty(source,'nextFrame',{get(){throw Error('unavailable');}});doc.textFrames.push(source);const c={FormalStore:FormalStore,app:{activeDocument:doc},TextType:{POINTTEXT:'point'},TextOrientation:{HORIZONTAL:'horizontal'}};vm.runInNewContext(src+';this.make=FormalStep1Adapter;',c);let b=F.create('日本'),p=c.make(doc,source);assert.equal(p.observe().status,'complete');const out={typename:'TextFrame',note:'formal-step1-output:v1;'+b.sourceFrameId+';other',contents:'x'};doc.textFrames.push(out);assert.throws(()=>p.inspect(b),/output-id-collision/);});
test('clone and apply work when JSON is unavailable',()=>{const fs=require('fs'),vm=require('vm'),src=fs.readFileSync(require('path').join(__dirname,'..','core.js'),'utf8'),c={JSON:undefined};vm.runInNewContext(src+';this.F=FormalStep1;',c);let b=c.F.create('日本');assert.equal(c.F.clone(b).textSnapshot,'日本');assert.ok(!src.includes('JSON.'));});
test('adapter keeps ruby size fixed and uses bounded tracking for width fit',()=>{const s=require('fs').readFileSync(require('path').join(__dirname,'..','adapter.jsx'),'utf8');assert.ok(s.includes('characterAttributes.tracking'));assert.ok(s.includes('tracking<-400'));assert.ok(s.includes('tracking>400'));assert.ok(!s.includes('size*=ratio'));});
test('reading length changes tracking without changing ruby size ratio',()=>{const fs=require('fs'),vm=require('vm'),s=fs.readFileSync(require('path').join(__dirname,'..','adapter.jsx'),'utf8'),c={};vm.runInNewContext(s+';this.t=FormalStep1Tracking;',c);const short=c.t(50,40,20,.5,5),long=c.t(50,40,20,.5,6);assert.notEqual(short,long);assert.equal(.5,.5);assert.ok(short<=400&&short>=-400&&long<=400&&long>=-400);});
