const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../../formal-step1/core.js'); global.FormalStep1=F; global.FormalStore=require('../../formal-step1/store.js');
const M=require('../multi.js'); global.FormalMulti=M; const Store=require('../multi-store.js');
const Long=require('../occurrences.js');
function second(frame){const a=F.create(frame.textSnapshot).annotation;a.sourceFrameId=frame.sourceFrameId;a.anchor={baseText:'張羅',startHint:1,beforeContext:'一',afterContext:''};a.reading='ちょうら';a.readingConfirmed=true;a.splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:3,baseText:'張羅',reading:'ちょうら',baseRevision:0,readingRevision:0}];return a;}
test('two annotations round trip in one frame and keep hints isolated',()=>{let b=M.create('一張羅');b.annotations[0].reading='いっちょうら';b.annotations[0].readingConfirmed=true;b.annotations[0].splitHints=[{baseBoundaryAfter:2,readingBoundaryAfter:5,baseText:'一張羅',reading:'いっちょうら',baseRevision:0,readingRevision:0}];b=M.add(b,second(b));let note=Store.write('foreign\n',b),r=Store.read(note);assert.ok(note.startsWith('foreign\n'));assert.equal(r.annotations.length,2);assert.equal(r.annotations[0].splitHints.length,1);assert.equal(r.annotations[1].splitHints[0].reading,'ちょうら');});
test('duplicate IDs and foreign source IDs are rejected',()=>{let b=M.create('一張羅'),a=second(b);assert.throws(()=>M.add(M.add(b,a),a),/duplicate-multi-annotation-id/);a.sourceFrameId='foreign';assert.throws(()=>M.add(b,a),/multi-source-frame-mismatch/);});
test('old Step 1 and Step 2 notes are not read as multi bundles',()=>{let b=F.create('一張羅'),old=FormalStore.write('foreign\n',b);assert.equal(Store.read(old),null);});
test('one unresolved annotation can be updated without mutating its sibling',()=>{let b=M.create('一張羅'),a=second(b);b=M.add(b,a);b.annotations[0].reviewReasons=['anchor-missing'];let next=M.update(b,b.annotations[1].annotationId,{reading:'ら変更',readingConfirmed:false,splitHints:[]});assert.deepEqual(next.annotations[0].reviewReasons,['anchor-missing']);assert.equal(next.annotations[1].reading,'ら変更');});
test('hint objects are deep-cloned and impossible hints are rejected',()=>{let b=M.create('一張羅');b.annotations[0].reading='いっちょうら';b.annotations[0].readingConfirmed=true;let h={baseBoundaryAfter:2,readingBoundaryAfter:5,baseText:'一張羅',reading:'いっちょうら',baseRevision:0,readingRevision:0};b.annotations[0].splitHints=[h];let copy=M.clone(b);copy.annotations[0].splitHints[0].readingBoundaryAfter=4;assert.equal(b.annotations[0].splitHints[0].readingBoundaryAfter,5);assert.throws(()=>M.update(b,b.annotations[0].annotationId,{splitHints:[{baseBoundaryAfter:3,readingBoundaryAfter:5,baseText:'別',reading:'いっちょうら',baseRevision:0,readingRevision:0}]}),/invalid-multi-split-hint/);});
test('split hints must remain strictly monotonic',()=>{let b=M.create('一張羅');b.annotations[0].reading='いっちょうら';b.annotations[0].readingConfirmed=true;assert.throws(()=>M.update(b,b.annotations[0].annotationId,{splitHints:[{baseBoundaryAfter:1,readingBoundaryAfter:5,baseText:'一張羅',reading:'いっちょうら',baseRevision:0,readingRevision:0},{baseBoundaryAfter:1,readingBoundaryAfter:6,baseText:'一張羅',reading:'いっちょうら',baseRevision:0,readingRevision:0}]}),/invalid-multi-split-hint/);});
test('malformed multi store cannot leak fields into a later read',()=>{let b=M.create('一張羅'),note=Store.write('',b),broken=note.replace(/revision=[^\n]+\n/,''),marker='[v2-formal-step2-multi:v1]';assert.throws(()=>Store.read(broken),/missing-multi-field/);assert.equal(Store.read(note).sourceFrameId,b.sourceFrameId);assert.equal((note.match(new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length,1);});
test('empty multi frame round trips with zero annotations',()=>{let b=M.createFrame('一張羅'),note=Store.write('foreign\n',b),r=Store.read(note);assert.equal(r.annotations.length,0);assert.ok(note.startsWith('foreign\n'));});
test('logical occurrences round trip with ranges, lineage, readings, and no-reading units',()=>{let logical=Long.extract('水戸藩士市田九衛門隆正');logical=Long.splitAt(logical,logical.occurrences[0].occurrenceId,[4,6,9]);logical=Long.setGroupReading(logical,logical.occurrences[1].groupId,'いちだ',true);logical=Long.setGroupReading(logical,logical.occurrences[3].groupId,'たかまさ',true);let b=M.createFrame(logical.textSnapshot);b.occurrences=logical.occurrences;let note=Store.write('foreign\n',b),r=Store.read(note);assert.deepEqual(r.occurrences.map(x=>({start:x.start,end:x.end,surface:x.surface,reading:x.reading})),logical.occurrences.map(x=>({start:x.start,end:x.end,surface:x.surface,reading:x.reading})));assert.deepEqual(r.occurrences[0].lineage,logical.occurrences[0].lineage);});
test('malformed logical occurrence payload is rejected without breaking v1',()=>{let b=M.createFrame('甲'),note=Store.write('',b),broken=note.replace('\n[/v2-formal-step2-multi]','\noccurrence.0=bad\n[/v2-formal-step2-multi]');assert.throws(()=>Store.read(broken),/invalid-multi-occurrence/);assert.equal(Store.read(note).annotations.length,0);});
