const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../../formal-step1/core.js');global.FormalStep1=F;global.FormalStore=require('../../formal-step1/store.js');
const M=require('../multi.js');global.FormalMulti=M;const S=require('../segments.js');global.FormalSegments=S;const P=require('../projection.js');global.FormalMultiProjection=P;const Long=require('../occurrences.js');const O=require('../orchestration.js');
function bundle(){let b=M.create('甲乙丙丁'),a=b.annotations[0];a.anchor={baseText:'甲乙',startHint:0,beforeContext:'',afterContext:'丙丁'};a.reading='こうおつ';a.readingConfirmed=true;let c=F.create('甲乙丙丁').annotation;c.sourceFrameId=b.sourceFrameId;c.anchor={baseText:'丙丁',startHint:2,beforeContext:'甲乙',afterContext:''};c.reading='へいてい';c.readingConfirmed=true;b=M.add(b,c);return b;}
const lines=[{start:0,end:1,geometry:{}},{start:1,end:2,geometry:{}},{start:2,end:3,geometry:{}},{start:3,end:4,geometry:{}}];
test('two annotations complete independently with annotation-relative lines',()=>{let b=bundle();b.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'甲乙',reading:'こうおつ',baseRevision:0,readingRevision:0}];b.annotations[1].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'丙丁',reading:'へいてい',baseRevision:0,readingRevision:0}];let r=O.planAll(b,'甲乙丙丁',{status:'complete',lines:lines});assert.equal(r.status,'complete');assert.deepEqual(r.results.map(x=>x.status),['complete','complete']);assert.deepEqual(r.results.map(x=>[x.sourceStart,x.sourceEnd]),[[0,2],[2,4]]);});
test('one missing anchor stays local and does not mutate sibling',()=>{let b=bundle();b.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'甲乙',reading:'こうおつ',baseRevision:0,readingRevision:0}];b.annotations[1].anchor.afterContext='不存在';let before=JSON.stringify(b.annotations[0]);let r=O.planAll(b,'甲乙丙丁x',{status:'complete',lines:[{start:0,end:1,geometry:{}},{start:1,end:2,geometry:{}},{start:2,end:5,geometry:{}}]});assert.equal(r.results[0].status,'complete');assert.equal(r.results[1].reasons[0],'anchor-missing');assert.equal(JSON.stringify(b.annotations[0]),before);});
test('annotation spanning a wrap receives relative intersections',()=>{let b=bundle();b.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'甲乙',reading:'こうおつ',baseRevision:0,readingRevision:0}];let r=O.planOne(b,b.annotations[0].annotationId,'甲乙丙丁',{status:'complete',lines:[{start:0,end:1,geometry:{}},{start:1,end:3,geometry:{}}]});assert.equal(r.status,'complete');assert.deepEqual(r.decision.segments.map(x=>x.baseText),['甲','乙']);});
test('ambiguous anchor remains annotation-local unresolved',()=>{let b=M.create('甲乙甲乙'),a=b.annotations[0];a.anchor={baseText:'甲乙',startHint:0,beforeContext:'',afterContext:''};a.reading='こうおつ';a.readingConfirmed=true;let r=O.planOne(b,a.annotationId,'甲乙甲乙x',{status:'complete',lines:[{start:0,end:5,geometry:{}}]});assert.equal(r.status,'unresolved');assert.equal(r.reasons[0],'anchor-ambiguous');});
test('nested edits passed to update do not alias caller values',()=>{let b=M.create('甲乙'),a=b.annotations[0],edit={anchor:{baseText:'甲乙',startHint:0,beforeContext:'',afterContext:''},style:{sizeRatio:.4,gapRatio:.2},offset:{inlineEm:1,blockEm:2},reviewReasons:['manual']};let n=M.update(b,a.annotationId,edit);edit.anchor.baseText='変更';edit.style.sizeRatio=.9;edit.offset.inlineEm=9;edit.reviewReasons.push('later');assert.equal(n.annotations[0].anchor.baseText,'甲乙');assert.equal(n.annotations[0].style.sizeRatio,.4);assert.equal(n.annotations[0].offset.inlineEm,1);assert.deepEqual(n.annotations[0].reviewReasons,['manual']);});
test('suppressed annotation is complete without render even when shared observation fails',()=>{let b=bundle(),a=b.annotations[0];a.enabled=false;let r=O.planOne(b,a.annotationId,'甲乙丙丁',{status:'failed',reasons:['outline-failed']});assert.equal(r.status,'complete');assert.equal(r.suppressed,true);assert.deepEqual(r.decision.segments,[]);});
test('unconfirmed reading and manual placement remain annotation-local reasons',()=>{let b=bundle(),a=b.annotations[0];a.reading='';a.readingConfirmed=false;a.placementMode='manual';let r=O.planOne(b,a.annotationId,'甲乙丙丁',{status:'complete',lines:lines});assert.equal(r.status,'unresolved');assert.deepEqual(r.reasons,['reading-unconfirmed','manual-placement']);});
test('suppressed or unresolved sibling does not change a complete annotation result',()=>{let b=bundle();b.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'甲乙',reading:'こうおつ',baseRevision:0,readingRevision:0}];b.annotations[1].enabled=false;let r=O.planAll(b,'甲乙丙丁',{status:'complete',lines:lines});assert.equal(r.results[0].status,'complete');assert.equal(r.results[1].suppressed,true);});
test('projectAndPlanAll projects only confirmed logical readings',()=>{let l=Long.extract('水戸藩士市田九衛門隆正');l=Long.splitAt(l,l.occurrences[0].occurrenceId,[4,6,9]);l=Long.setGroupReading(l,l.occurrences[1].groupId,'いちだ',true);l=Long.setGroupReading(l,l.occurrences[3].groupId,'たかまさ',true);let b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let r=O.projectAndPlanAll(b,l.textSnapshot,{status:'complete',lines:[{start:0,end:11,geometry:{}}]});assert.equal(r.bundle.annotations.length,2);assert.deepEqual(r.plan.results.map(x=>x.status),['complete','complete']);});
test('projectAndPlanAll retires one disabled occurrence only',()=>{let l=Long.extract('水戸藩士市田九衛門隆正');l=Long.splitAt(l,l.occurrences[0].occurrenceId,[4,6,9]);l=Long.setGroupReading(l,l.occurrences[1].groupId,'いちだ',true);l=Long.setGroupReading(l,l.occurrences[3].groupId,'たかまさ',true);let b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let first=O.projectAndPlanAll(b,l.textSnapshot,{status:'complete',lines:[{start:0,end:11,geometry:{}}]});l.occurrences[1].enabled=false;let second=O.projectAndPlanAll(Object.assign({},first.bundle,{occurrences:l.occurrences}),l.textSnapshot,{status:'complete',lines:[{start:0,end:11,geometry:{}}]});assert.deepEqual(second.bundle.annotations.map(a=>a.anchor.baseText),['隆正']);});
test('projectAndPlanAll preserves one wrapped logical occurrence through two render segments',()=>{let l=Long.extract('一張羅');l.occurrences[0].reading='いっちょうら';l.occurrences[0].readingConfirmed=true;let b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let seeded=O.projectAndPlanAll(b,l.textSnapshot,{status:'complete',lines:[{start:0,end:3,geometry:{}}]});seeded.bundle.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'一張羅',reading:'いっちょうら',baseRevision:0,readingRevision:0}];let r=O.projectAndPlanAll(seeded.bundle,l.textSnapshot,{status:'complete',lines:[{start:0,end:1,geometry:{}},{start:1,end:3,geometry:{}}]});assert.equal(r.bundle.annotations.length,1);assert.equal(r.plan.results.length,1);assert.equal(r.plan.results[0].decision.segments.length,2);});
test('unrelated occurrence-prefix annotation is preserved',()=>{let l=Long.extract('一張羅');l.occurrences[0].reading='いっちょうら';l.occurrences[0].readingConfirmed=true;let b=M.createFrame(l.textSnapshot),manual=F.create(l.textSnapshot).annotation;manual.annotationId='v2-occurrence-123-0';manual.sourceFrameId=b.sourceFrameId;manual.anchor={baseText:'一張羅',startHint:0,beforeContext:'',afterContext:''};manual.reading='手動';manual.readingConfirmed=true;manual.splitHints=[];b=M.add(b,manual);b.occurrences=l.occurrences;let r=O.projectAndPlanAll(b,l.textSnapshot,{status:'complete',lines:[{start:0,end:3,geometry:{}}]});assert.ok(r.bundle.annotations.some(a=>a.annotationId==='v2-occurrence-123-0'));});
