const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../../formal-step1/core.js');global.FormalStep1=F;global.FormalStore=require('../../formal-step1/store.js');
const M=require('../multi.js');global.FormalMulti=M;const S=require('../segments.js');global.FormalSegments=S;const O=require('../orchestration.js');
function bundle(){let b=M.create('甲乙丙丁'),a=b.annotations[0];a.anchor={baseText:'甲乙',startHint:0,beforeContext:'',afterContext:'丙丁'};a.reading='こうおつ';a.readingConfirmed=true;let c=F.create('甲乙丙丁').annotation;c.sourceFrameId=b.sourceFrameId;c.anchor={baseText:'丙丁',startHint:2,beforeContext:'甲乙',afterContext:''};c.reading='へいてい';c.readingConfirmed=true;b=M.add(b,c);return b;}
const lines=[{start:0,end:1,geometry:{}},{start:1,end:2,geometry:{}},{start:2,end:3,geometry:{}},{start:3,end:4,geometry:{}}];
test('two annotations complete independently with annotation-relative lines',()=>{let b=bundle();b.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'甲乙',reading:'こうおつ',baseRevision:0,readingRevision:0}];b.annotations[1].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'丙丁',reading:'へいてい',baseRevision:0,readingRevision:0}];let r=O.planAll(b,'甲乙丙丁',{status:'complete',lines:lines});assert.equal(r.status,'complete');assert.deepEqual(r.results.map(x=>x.status),['complete','complete']);assert.deepEqual(r.results.map(x=>[x.sourceStart,x.sourceEnd]),[[0,2],[2,4]]);});
test('one missing anchor stays local and does not mutate sibling',()=>{let b=bundle();b.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'甲乙',reading:'こうおつ',baseRevision:0,readingRevision:0}];b.annotations[1].anchor.afterContext='不存在';let before=JSON.stringify(b.annotations[0]);let r=O.planAll(b,'甲乙丙丁x',{status:'complete',lines:[{start:0,end:1,geometry:{}},{start:1,end:2,geometry:{}},{start:2,end:5,geometry:{}}]});assert.equal(r.results[0].status,'complete');assert.equal(r.results[1].reasons[0],'anchor-missing');assert.equal(JSON.stringify(b.annotations[0]),before);});
test('annotation spanning a wrap receives relative intersections',()=>{let b=bundle();b.annotations[0].splitHints=[{baseBoundaryAfter:1,readingBoundaryAfter:2,baseText:'甲乙',reading:'こうおつ',baseRevision:0,readingRevision:0}];let r=O.planOne(b,b.annotations[0].annotationId,'甲乙丙丁',{status:'complete',lines:[{start:0,end:1,geometry:{}},{start:1,end:3,geometry:{}}]});assert.equal(r.status,'complete');assert.deepEqual(r.decision.segments.map(x=>x.baseText),['甲','乙']);});
test('ambiguous anchor remains annotation-local unresolved',()=>{let b=M.create('甲乙甲乙'),a=b.annotations[0];a.anchor={baseText:'甲乙',startHint:0,beforeContext:'',afterContext:''};a.reading='こうおつ';a.readingConfirmed=true;let r=O.planOne(b,a.annotationId,'甲乙甲乙x',{status:'complete',lines:[{start:0,end:5,geometry:{}}]});assert.equal(r.status,'unresolved');assert.equal(r.reasons[0],'anchor-ambiguous');});
test('nested edits passed to update do not alias caller values',()=>{let b=M.create('甲乙'),a=b.annotations[0],edit={anchor:{baseText:'甲乙',startHint:0,beforeContext:'',afterContext:''},style:{sizeRatio:.4,gapRatio:.2},offset:{inlineEm:1,blockEm:2},reviewReasons:['manual']};let n=M.update(b,a.annotationId,edit);edit.anchor.baseText='変更';edit.style.sizeRatio=.9;edit.offset.inlineEm=9;edit.reviewReasons.push('later');assert.equal(n.annotations[0].anchor.baseText,'甲乙');assert.equal(n.annotations[0].style.sizeRatio,.4);assert.equal(n.annotations[0].offset.inlineEm,1);assert.deepEqual(n.annotations[0].reviewReasons,['manual']);});
