const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'..','persistence-adapter.jsx'),'utf8');
function load(store,bridge){const context={FormalMultiStore:store,encodeURIComponent:encodeURIComponent,decodeURIComponent:decodeURIComponent,BridgeTalk:bridge};vm.runInNewContext(source+';this.adapter=FormalMultiPersistenceAdapter;',context);return context.adapter;}
const identity={uuid:'uuid-1',documentPath:'C:/doc.ai'};
test('serializes before direct persistence and succeeds without rereading source note',()=>{let writes=0,stored='old',sourceFrame={set note(v){stored=v},get note(){throw Error('palette reread must not occur')},contents:'甲',typename:'TextFrame'},adapter=load({write:(note,bundle)=>{writes++;assert.equal(note,'old');return 'new'}},null),result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{});assert.equal(result.status,'success');assert.equal(result.strategy,'A-direct-source-note');assert.equal(writes,1);assert.equal(stored,'new');});
test('falls from A to B automatically and reports B success',()=>{let sent=false,sourceFrame={set note(v){throw Error('there is no document')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>{sent=true;this.onResult({body:'B-bridge-talk:success'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),success=null,result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{success:value=>{success=value}});assert.equal(result.status,'pending');assert.equal(sent,true);assert.equal(success.strategy,'B-bridge-talk');});
test('bridge-only persistence never receives a source DOM object',()=>{let sent=false,FakeBridgeTalk=function(){this.send=()=>{sent=true;this.onResult({body:'B-bridge-talk:success'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),success=null,result=adapter.saveBridgeOnly('甲','old',{textSnapshot:'甲'},identity,{success:value=>{success=value}});assert.equal(result.status,'pending');assert.equal(sent,true);assert.equal(success.strategy,'B-bridge-talk');});
test('aggregates A and B failures without a third speculative write',()=>{let sourceFrame={set note(v){throw Error('A failure')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>{this.onError({body:'B failure'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),failure=null,result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{failure:diagnostics=>{failure=diagnostics}});assert.equal(result.status,'pending');assert.equal(Array.prototype.join.call(failure,'|'),'A-direct-source-note: A failure|B-bridge-talk: B failure');});
test('records send false as queued-or-not-sent and arms timeout',()=>{let pending=null,sourceFrame={set note(v){throw Error('A failure')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>false};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{pending:diagnostics=>{pending=diagnostics}});assert.equal(result.status,'pending');assert.equal(pending[1],'B-bridge-talk: send=false (queued-or-not-sent)');assert.equal(result.bridge.timeout,30);});
test('timeout completes B with a named diagnostic',()=>{let failure=null,sourceFrame={set note(v){throw Error('A failure')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>{this.onTimeout({body:'timeout body'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk);adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{failure:diagnostics=>{failure=diagnostics}});assert.equal(failure[1],'B-bridge-talk: timeout:timeout body');});
test('bridge body contains identity, snapshot, cached-note, and supported frame validation',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.bridgeBody('甲','old','new',identity);assert.match(body,/getPageItemFromUuid/);assert.match(body,/origin-document-mismatch/);assert.match(body,/source-snapshot-mismatch/);assert.match(body,/source-note-target-mismatch/);assert.match(body,/TextType\.AREATEXT/);assert.match(body,/TextType\.POINTTEXT/);assert.match(body,/TextOrientation\.HORIZONTAL/);});
test('rendered bridge carries shared renderer sources and transaction rollback contract',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new',identity,{revision:0,sourceFrameId:'frame-1'},[{annotationId:'a',annotation:null}],{step1:'STEP1_SOURCE',segments:'SEGMENTS_SOURCE',orchestration:'ORCHESTRATION_SOURCE',adapter:'ADAPTER_SOURCE'});assert.match(body,/STEP1_SOURCE/);assert.match(body,/SEGMENTS_SOURCE/);assert.match(body,/ORCHESTRATION_SOURCE/);assert.match(body,/ADAPTER_SOURCE/);assert.match(body,/getPageItemFromUuid/);assert.match(body,/renderAndStoreTransaction/);assert.match(body,/origin-document-mismatch/);assert.match(body,/source-note-target-mismatch/);});
test('rendered bridge exposes named host-stage diagnostics',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new',identity,{revision:0,sourceFrameId:'frame-1'},[{annotationId:'a',annotation:null}],{step1:'STEP1_SOURCE',segments:'SEGMENTS_SOURCE',orchestration:'ORCHESTRATION_SOURCE',adapter:'ADAPTER_SOURCE'},'C:/Temp/formal-multi-host.log');for(const stage of ['host-entry','step1-eval-start','step1-eval-end','segments-eval-start','segments-eval-end','orchestration-eval-start','orchestration-eval-end','adapter-eval-start','adapter-eval-end','host-validation-start','host-validation-end','adapter-constructed','observe-start','observe-end','plan-start','plan-end','transaction-start','transaction-end','note-commit-start','note-commit-end','return'])assert.match(body,new RegExp(stage.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')));assert.match(body,/File\(stagePath\)/);assert.match(body,/stageFile\.open\("w"\)/);assert.match(body,/stageFile\.write/);assert.match(body,/stageFile\.close/);});
test('render failure has a persistence-success result and failure note path',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new','failed-note',identity,{revision:0,sourceFrameId:'frame-1'},[{annotationId:'a',annotation:null}],{step1:'STEP1_SOURCE',segments:'SEGMENTS_SOURCE',orchestration:'ORCHESTRATION_SOURCE',adapter:'ADAPTER_SOURCE'});assert.match(body,/renderFailure/);assert.match(body,/B-render-persist:render-failed/);assert.match(body,/persistence-after-render-failure-mismatch/);});
test('render bridge verifies a request-scoped heartbeat before send',()=>{const s=fs.readFileSync(path.join(__dirname,'..','persistence-adapter.jsx'),'utf8');assert.match(s,/function verifyStagePath/);assert.match(s,/stage-file-not-writable/);assert.match(s,/pre-send/);assert.match(s,/requestId/);});
