const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'..','persistence-adapter.jsx'),'utf8');
const F=require('../../formal-step1/core.js');global.FormalStep1=F;const M=require('../multi.js');global.FormalMulti=M;const Long=require('../occurrences.js');const P=require('../projection.js');global.FormalMultiProjection=P;const R=require('../multi-renderer.js');global.FormalMultiRenderer=R;
function load(store,bridge){const context={FormalMultiStore:store,encodeURIComponent:encodeURIComponent,decodeURIComponent:decodeURIComponent,BridgeTalk:bridge,File:function(){return {exists:true,open:()=>true,write:()=>true,close:()=>{}}}};vm.runInNewContext(source+';this.adapter=FormalMultiPersistenceAdapter;',context);return context.adapter;}
const identity={uuid:'uuid-1',documentPath:'C:/doc.ai'};
test('serializes before direct persistence and succeeds without rereading source note',()=>{let writes=0,stored='old',sourceFrame={set note(v){stored=v},get note(){throw Error('palette reread must not occur')},contents:'甲',typename:'TextFrame'},adapter=load({write:(note,bundle)=>{writes++;assert.equal(note,'old');return 'new'}},null),result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{});assert.equal(result.status,'success');assert.equal(result.strategy,'A-direct-source-note');assert.equal(writes,1);assert.equal(stored,'new');});
test('falls from A to B automatically and reports B success',()=>{let sent=false,sourceFrame={set note(v){throw Error('there is no document')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>{sent=true;this.onResult({body:'B-bridge-talk:success'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),success=null,result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{success:value=>{success=value}});assert.equal(result.status,'pending');assert.equal(sent,true);assert.equal(success.strategy,'B-bridge-talk');});
test('bridge-only persistence never receives a source DOM object',()=>{let sent=false,FakeBridgeTalk=function(){this.send=()=>{sent=true;this.onResult({body:'B-bridge-talk:success'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),success=null,result=adapter.saveBridgeOnly('甲','old',{textSnapshot:'甲'},identity,{success:value=>{success=value}});assert.equal(result.status,'pending');assert.equal(sent,true);assert.equal(success.strategy,'B-bridge-talk');});
test('aggregates A and B failures without a third speculative write',()=>{let sourceFrame={set note(v){throw Error('A failure')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>{this.onError({body:'B failure'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),failure=null,result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{failure:diagnostics=>{failure=diagnostics}});assert.equal(result.status,'pending');assert.equal(Array.prototype.join.call(failure,'|'),'A-direct-source-note: A failure|B-bridge-talk: B failure');});
test('records send false as queued-or-not-sent and arms timeout',()=>{let pending=null,sourceFrame={set note(v){throw Error('A failure')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>false};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),result=adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{pending:diagnostics=>{pending=diagnostics}});assert.equal(result.status,'pending');assert.equal(pending[1],'B-bridge-talk: send=false (queued-or-not-sent)');assert.equal(result.bridge.timeout,30);});
test('timeout completes B with a named diagnostic',()=>{let failure=null,sourceFrame={set note(v){throw Error('A failure')},contents:'甲',typename:'TextFrame'},FakeBridgeTalk=function(){this.send=()=>{this.onTimeout({body:'timeout body'});return true}};FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk);adapter.save(sourceFrame,'old',{textSnapshot:'甲'},identity,{failure:diagnostics=>{failure=diagnostics}});assert.equal(failure[1],'B-bridge-talk: timeout:timeout body');});
test('bridge body contains identity, snapshot, cached-note, and supported frame validation',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.bridgeBody('甲','old','new',identity);assert.match(body,/getPageItemFromUuid/);assert.match(body,/origin-document-mismatch/);assert.match(body,/source-snapshot-mismatch/);assert.match(body,/source-note-target-mismatch/);assert.match(body,/TextType\.AREATEXT/);assert.match(body,/TextType\.POINTTEXT/);assert.match(body,/TextOrientation\.HORIZONTAL/);});
test('rendered bridge carries shared renderer sources and transaction rollback contract',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new',identity,{revision:0,sourceFrameId:'frame-1'},[{annotationId:'a',annotation:null}],{step1:'STEP1_SOURCE',segments:'SEGMENTS_SOURCE',orchestration:'ORCHESTRATION_SOURCE',adapter:'ADAPTER_SOURCE'});assert.match(body,/STEP1_SOURCE/);assert.match(body,/SEGMENTS_SOURCE/);assert.match(body,/ORCHESTRATION_SOURCE/);assert.match(body,/ADAPTER_SOURCE/);assert.match(body,/getPageItemFromUuid/);assert.match(body,/renderAndStoreTransaction/);assert.match(body,/origin-document-mismatch/);assert.match(body,/source-note-target-mismatch/);});
test('rendered bridge loads existing runtime files without source injection',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new',identity,{revision:0,sourceFrameId:'frame-1'},[{annotationId:'a',annotation:null}],{step1:'C:/runtime/core.js',segments:'C:/runtime/segments.js',orchestration:'C:/runtime/orchestration.js',appearance:'C:/runtime/appearance.js',adapter:'C:/runtime/adapter.jsx'},'C:/Temp/formal-multi-host.log');assert.ok(body.indexOf('core.js')<body.indexOf('segments.js'));assert.ok(body.indexOf('segments.js')<body.indexOf('orchestration.js'));assert.ok(body.indexOf('orchestration.js')<body.indexOf('adapter.jsx'));assert.match(body,/\$\.evalFile\(File\(decodeURIComponent/);assert.doesNotMatch(body,/eval\(decodeURIComponent/);assert.doesNotMatch(body,/stage\(/);assert.doesNotMatch(body,/stageFile/);});
test('rendered bridge checks globals after ordered runtime loading',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new',identity,{revision:0,sourceFrameId:'frame-1'},[],{step1:'C:/runtime/core.js',segments:'C:/runtime/segments.js',orchestration:'C:/runtime/orchestration.js',adapter:'C:/runtime/adapter.jsx'});assert.match(body,/FormalStep1===\"undefined\"/);assert.match(body,/FormalSegments===\"undefined\"/);assert.match(body,/FormalMultiOrchestration===\"undefined\"/);assert.match(body,/FormalStep2Adapter===\"undefined\"/);assert.match(body,/runtime-symbol-missing/);});
test('render failure has an explicit persistence-failure result path',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new','failed-note',identity,{revision:0,sourceFrameId:'frame-1'},[{annotationId:'a',annotation:null}],{step1:'STEP1_SOURCE',segments:'SEGMENTS_SOURCE',orchestration:'ORCHESTRATION_SOURCE',adapter:'ADAPTER_SOURCE'});assert.match(body,/renderFailure/);assert.match(body,/B-render-persist:render-failed/);assert.match(body,/persistenceError/);assert.match(body,/B-render-persist:persistence-failed/);});
test('persistence failure is routed to failure callback while render failure remains a success result',()=>{function FakeBridgeTalk(){this.send=()=>{this.onResult({body:FakeBridgeTalk.body});return true}}FakeBridgeTalk.getSpecifier=()=> 'illustrator-30.8';let adapter=load({write:()=> 'new'},FakeBridgeTalk),failure=null,success=null;FakeBridgeTalk.body='B-render-persist:persistence-failed';adapter.saveRendered('甲','old',{textSnapshot:'甲'},identity,[],{step1:'a',segments:'b',orchestration:'c',appearance:'e',adapter:'d'},{failure:v=>{failure=v},success:v=>{success=v}},FakeBridgeTalk);assert.ok(failure);assert.equal(success,null);FakeBridgeTalk.body='B-render-persist:render-failed';failure=null;adapter.saveRendered('甲','old',{textSnapshot:'甲'},identity,[],{step1:'a',segments:'b',orchestration:'c',appearance:'e',adapter:'d'},{failure:v=>{failure=v},success:v=>{success=v}},FakeBridgeTalk);assert.equal(failure,null);assert.equal(success.renderStatus,'failed');});
test('unresolved render plans clean managed output while persisting render failure state',()=>{let adapter=load({write:()=> 'new'},null),body=adapter.renderedBridgeBody('甲','old','new','failed-note',identity,{revision:0,sourceFrameId:'frame-1'},[{annotationId:'a',annotation:{annotationId:'a',sourceFrameId:'frame-1',anchor:{baseText:'甲',startHint:0,beforeContext:'',afterContext:''},reading:'か',readingConfirmed:true,enabled:true,placementMode:'auto',splitHints:[]}}],{step1:'STEP1_SOURCE',segments:'SEGMENTS_SOURCE',orchestration:'ORCHESTRATION_SOURCE',adapter:'ADAPTER_SOURCE'});assert.match(body,/renderError=\"render-unresolved\"/);assert.match(body,/segments:\[\]\}/);assert.match(body,/renderAdapter\.renderAndStoreTransaction/);assert.match(body,/frame\.note=renderError\?renderFailure:next/);});
test('render bridge verifies a request-scoped heartbeat before send',()=>{const s=fs.readFileSync(path.join(__dirname,'..','persistence-adapter.jsx'),'utf8');assert.match(s,/function verifyStagePath/);assert.match(s,/stage-file-not-writable/);assert.match(s,/pre-send/);assert.match(s,/requestId/);});
test('split child survives confirmed and unconfirmed persistence preparation as a full bundle',()=>{
  const runtimePaths={step1:'C:/runtime/core.js',segments:'C:/runtime/segments.js',orchestration:'C:/runtime/orchestration.js',appearance:'C:/runtime/appearance.js',adapter:'C:/runtime/adapter.jsx'};
  for(const confirmed of [true,false]){
    let logical=Long.extract('甲乙'),frame=M.createFrame(logical.textSnapshot);
    logical=Long.splitAt(logical,logical.occurrences[0].occurrenceId,[1]);
    logical.occurrences[1].reading=confirmed?'おつ':'';logical.occurrences[1].readingConfirmed=confirmed;
    frame=M.replaceOccurrences(frame,logical.occurrences);frame=M.validate(frame);
    const projected=P.project(frame);M.validate(projected);const specs=R.specifications(projected);
    assert.equal(new Set(frame.occurrences.map(x=>x.occurrenceId)).size,frame.occurrences.length);
    assert.equal(new Set(specs.map(x=>x.annotationId)).size,specs.length);
    const body=load({write:()=> 'new'},null).renderedBridgeBody(frame.textSnapshot,'old','new',identity,projected,specs,runtimePaths);
    assert.doesNotThrow(()=>new vm.Script(body,{filename:'split-child-generated-bridge.jsx'}));
    assert.equal(projected.sourceFrameId,frame.sourceFrameId);
    assert.equal(projected.revision,frame.revision);
  }
});
