const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../../formal-step1/core.js'); global.FormalStep1=F; global.FormalStore=require('../../formal-step1/store.js');
const M=require('../multi.js'); global.FormalMulti=M; const Long=require('../occurrences.js'); const P=require('../projection.js');
function logical(){let b=Long.extract('水戸藩士市田九衛門隆正');b=Long.splitAt(b,b.occurrences[0].occurrenceId,[4,6,9]);b=Long.setGroupReading(b,b.occurrences[1].groupId,'いちだ',true);b=Long.setGroupReading(b,b.occurrences[3].groupId,'たかまさ',true);return b;}
test('projects only enabled confirmed readings and keeps no-reading units logical-only',()=>{let l=logical(),b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let p=P.project(b);assert.deepEqual(p.annotations.map(a=>({base:a.anchor.baseText,reading:a.reading})),[{base:'市田',reading:'いちだ'},{base:'隆正',reading:'たかまさ'}]);});
test('projection is idempotent and stable by occurrence identity',()=>{let l=logical(),b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let p=P.project(b),again=P.project(p);assert.equal(again.annotations.length,2);assert.deepEqual(again.annotations.map(a=>a.annotationId),p.annotations.map(a=>a.annotationId));});
test('disabling or clearing one occurrence retires only its annotation',()=>{let l=logical(),b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let p=P.project(b);l.occurrences[1].enabled=false;b.occurrences=l.occurrences;let next=P.project(Object.assign({},p,{occurrences:l.occurrences}));assert.equal(next.annotations.length,1);assert.equal(next.annotations[0].anchor.baseText,'隆正');});
test('same occurrence preserves style, offset, and hints; reading change clears hints',()=>{let l=logical(),b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let p=P.project(b),a=p.annotations[0];a.style.sizeRatio=0.8;a.offset.inlineEm=2;a.splitHints=[];let same=P.project(p);assert.equal(same.annotations[0].style.sizeRatio,0.8);assert.equal(same.annotations[0].offset.inlineEm,2);l.occurrences[1].reading='いちた';b=Object.assign({},p,{occurrences:l.occurrences});let changed=P.project(b);assert.equal(changed.annotations[0].reading,'いちた');assert.deepEqual(changed.annotations[0].splitHints,[]);});
test('one wrapped logical occurrence still projects to one annotation',()=>{let l=Long.extract('一張羅'),b=M.createFrame(l.textSnapshot);l.occurrences[0].reading='いっちょうら';l.occurrences[0].readingConfirmed=true;b.occurrences=l.occurrences;let p=P.project(b);assert.equal(p.annotations.length,1);});
test('projection normalizes shared state from the logical occurrence',()=>{let l=logical(),b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let p=P.project(b),a=p.annotations[0];a.enabled=false;a.readingConfirmed=false;a.reviewReasons=['stale'];let next=P.project(p);assert.equal(next.annotations[0].enabled,true);assert.equal(next.annotations[0].readingConfirmed,true);assert.deepEqual(next.annotations[0].reviewReasons,[]);assert.equal(next.annotations[0].anchor.beforeContext,'水戸藩士');});
