const test=require('node:test'),assert=require('node:assert/strict'),A=require('../selection-adapter.jsx');
const types={AREATEXT:'area',POINTTEXT:'point',PATHTEXT:'path'},orient={HORIZONTAL:'horizontal',VERTICAL:'vertical'};
function selection(){const source={typename:'TextFrame',kind:'area',orientation:'horizontal',contents:'甲乙丙丁',textRange:{start:10}};return {source,items:[{typename:'TextRange',parent:source,start:12,end:14}]};}
test('resolves one horizontal area text range to source-relative selection',()=>{let s=selection(),r=A.resolve(s.items,types,orient);assert.equal(r.sourceFrame,s.source);assert.deepEqual({start:r.start,end:r.end,text:r.text},{start:2,end:4,text:'丙丁'});});
test('resolves direct TextRange selection through its story frame',()=>{let s=selection(),item={typename:'TextRange',story:{textFrames:[s.source]},start:12,end:14};let r=A.resolve(item,types,orient);assert.equal(r.sourceFrame,s.source);assert.deepEqual({start:r.start,end:r.end,text:r.text},{start:2,end:4,text:'丙丁'});});
test('rejects no selection, multi selection, frame selection, and vertical text',()=>{let s=selection();assert.throws(()=>A.resolve([],types,orient),/single-text-selection-required/);assert.throws(()=>A.resolve([s.items[0],s.items[0]],types,orient),/single-text-selection-required/);assert.throws(()=>A.resolve([s.source],types,orient),/text-range-selection-required/);s.source.orientation='vertical';assert.throws(()=>A.resolve(s.items,types,orient),/area-text-horizontal-only/);});
test('rejects zero length and out of range ranges',()=>{let s=selection(),item=s.items[0];item.start=12;item.end=12;assert.throws(()=>A.resolve([item],types,orient),/invalid-text-selection/);item.start=-1;item.end=12;assert.throws(()=>A.resolve([item],types,orient),/invalid-text-selection/);});
test('source-frame resolver accepts horizontal area and point text',()=>{let area={typename:'TextFrame',kind:'area',orientation:'horizontal',contents:'甲',textRange:{start:0}},point={typename:'TextFrame',kind:'point',orientation:'horizontal',contents:'乙',textRange:{start:0}};assert.equal(A.resolveFrame([area],types,orient).sourceFrame,area);assert.equal(A.resolveFrame([point],types,orient).sourceFrame,point);});
test('source-frame resolver rejects vertical and path text',()=>{let vertical={typename:'TextFrame',kind:'point',orientation:'vertical',contents:'甲'},path={typename:'TextFrame',kind:'path',orientation:'horizontal',contents:'乙'};assert.throws(()=>A.resolveFrame([vertical],types,orient),/text-frame-vertical-unsupported/);assert.throws(()=>A.resolveFrame([path],types,orient),/text-frame-kind-unsupported/);});
test('source-frame resolver reports the named winning strategy',()=>{let direct={typename:'TextFrame',kind:'point',orientation:'horizontal',contents:'甲'};assert.equal(A.resolveFrame(direct,types,orient).strategy,'A-direct-selection');assert.equal(A.resolveFrame([direct],types,orient).strategy,'B-selection-array-first');});
test('source-frame resolver falls through from range parent to story frame',()=>{let source={typename:'TextFrame',kind:'area',orientation:'horizontal',contents:'甲乙'},range={typename:'TextRange',parent:{typename:'TextFrame',kind:'path',orientation:'horizontal',contents:'x'},story:{textFrames:[source]}};let result=A.resolveFrame([range],types,orient);assert.equal(result.sourceFrame,source);assert.equal(result.strategy,'D-text-range-story-frame');});
test('source-frame resolver aggregates every failed strategy',()=>{let path={typename:'TextFrame',kind:'path',orientation:'horizontal',contents:'甲'};assert.throws(()=>A.resolveFrame([path],types,orient),error=>error.message.indexOf('source-frame-resolution-failed')>=0&&error.message.indexOf('A-direct-selection')>=0&&error.message.indexOf('B-selection-array-first')>=0&&error.message.indexOf('C-text-range-parent')>=0&&error.message.indexOf('D-text-range-story-frame')>=0);});
