const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../../formal-step1/core.js');global.FormalStep1=F;global.FormalStore=require('../../formal-step1/store.js');const M=require('../multi.js');global.FormalMulti=M;const W=require('../workflow.js');const Long=require('../occurrences.js');const P=require('../projection.js');
function base(){return M.createFrame('甲乙丙丁');}
test('two explicit selections create source-relative annotations',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);assert.equal(b.annotations.length,2);assert.equal(b.annotations[0].anchor.baseText,'甲乙');assert.equal(b.annotations[0].anchor.startHint,0);assert.equal(b.annotations[1].anchor.baseText,'丙丁');assert.equal(b.annotations[1].anchor.startHint,2);});
test('reading edit leaves sibling unchanged',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);let id=b.annotations[0].annotationId,n=W.setReading(b,id,'こうおつ');assert.equal(n.annotations[0].reading,'こうおつ');assert.equal(n.annotations[1].reading,'');});
test('suppression removes an annotation from unresolved queue without deleting it',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);let r=[{annotationId:b.annotations[0].annotationId,status:'unresolved'},{annotationId:b.annotations[1].annotationId,status:'unresolved'}],n=W.setEnabled(b,b.annotations[0].annotationId,false);assert.deepEqual(W.reviewQueue(b,r),[b.annotations[0].annotationId,b.annotations[1].annotationId]);assert.deepEqual(W.reviewQueue(n,[{annotationId:n.annotations[0].annotationId,status:'complete'},{annotationId:n.annotations[1].annotationId,status:'unresolved'}]),[n.annotations[1].annotationId]);assert.equal(n.annotations.length,2);});
test('previous and next unresolved navigation is deterministic',()=>{let q=['a','c','f'];assert.equal(W.navigate(q,'c',-1),'a');assert.equal(W.navigate(q,'c',1),'f');assert.equal(W.navigate(q,'a',-1),null);assert.equal(W.navigate(q,'f',1),null);assert.equal(W.navigate(q,'missing',1),'a');});
test('failed frame result is excluded while unresolved result remains queued',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);assert.deepEqual(W.reviewQueue(b,[{annotationId:b.annotations[0].annotationId,status:'failed'},{annotationId:b.annotations[1].annotationId,status:'unresolved'}]),[b.annotations[1].annotationId]);});
test('empty and out-of-range selections are rejected',()=>{let b=base();assert.throws(()=>W.addSelection(b,b.textSnapshot,1,1),/invalid-source-selection/);assert.throws(()=>W.addSelection(b,b.textSnapshot,-1,2),/invalid-source-selection/);assert.throws(()=>W.addSelection(b,b.textSnapshot,0.5,2),/invalid-source-selection/);assert.throws(()=>W.addSelection(b,b.textSnapshot,0,Infinity),/invalid-source-selection/);assert.throws(()=>W.addSelection(b,'別文',0,1),/source-snapshot-mismatch/);});
test('reading confirmation removes only reading-unconfirmed and empty reading restores it',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);let id=b.annotations[0].annotationId;b.annotations[0].reviewReasons.push('anchor-missing');let confirmed=W.setReading(b,id,'こうおつ');assert.deepEqual(confirmed.annotations[0].reviewReasons,['anchor-missing']);let empty=W.setReading(confirmed,id,'',false);assert.deepEqual(empty.annotations[0].reviewReasons,['anchor-missing','reading-unconfirmed']);});
test('selection lookup restores exact persisted annotation and rejects ambiguity',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);assert.equal(W.findSelection(b,b.sourceFrameId,b.textSnapshot,0,2),b.annotations[0].annotationId);assert.equal(W.findSelection(b,b.sourceFrameId,b.textSnapshot,1,3),null);b=W.addSelection(b,b.textSnapshot,0,2);assert.throws(()=>W.findSelection(b,b.sourceFrameId,b.textSnapshot,0,2),/ambiguous-selection-match/);});
test('long-text edits preserve occurrence identity and project only confirmed enabled readings',()=>{let l=Long.extract('甲乙 甲乙 丙'),b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;let first=l.occurrences[0],second=l.occurrences[1];b=W.setOccurrenceReading(b,first.occurrenceId,'こうおつ',true);b=W.setOccurrenceEnabled(b,second.occurrenceId,false);let p=P.project(b);assert.equal(p.occurrences[0].occurrenceId,first.occurrenceId);assert.equal(p.occurrences[1].occurrenceId,second.occurrenceId);assert.deepEqual(p.annotations.map(a=>({base:a.anchor.baseText,start:a.anchor.startHint,reading:a.reading})),[{base:'甲乙',start:0,reading:'こうおつ'}]);});
test('long-text reading confirmation is cleared when reading becomes empty',()=>{let l=Long.extract('甲'),b=M.createFrame(l.textSnapshot);b.occurrences=l.occurrences;b=W.setOccurrenceReading(b,l.occurrences[0].occurrenceId,'こう',true);let next=W.setOccurrenceReading(b,l.occurrences[0].occurrenceId,'',true);assert.equal(next.occurrences[0].readingConfirmed,false);assert.equal(P.project(next).annotations.length,0);});
