const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../../formal-step1/core.js');global.FormalStep1=F;global.FormalStore=require('../../formal-step1/store.js');const M=require('../multi.js');global.FormalMulti=M;const W=require('../workflow.js');
function base(){return M.create('甲乙丙丁');}
test('two explicit selections create source-relative annotations',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);assert.equal(b.annotations.length,3);assert.equal(b.annotations[1].anchor.baseText,'甲乙');assert.equal(b.annotations[1].anchor.startHint,0);assert.equal(b.annotations[2].anchor.baseText,'丙丁');assert.equal(b.annotations[2].anchor.startHint,2);});
test('reading edit leaves sibling unchanged',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);let id=b.annotations[1].annotationId,n=W.setReading(b,id,'こうおつ');assert.equal(n.annotations[1].reading,'こうおつ');assert.equal(n.annotations[2].reading,'');});
test('suppression removes an annotation from unresolved queue without deleting it',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);let r=[{annotationId:b.annotations[1].annotationId,status:'unresolved'},{annotationId:b.annotations[2].annotationId,status:'unresolved'}],n=W.setEnabled(b,b.annotations[1].annotationId,false);assert.deepEqual(W.reviewQueue(b,r),[b.annotations[1].annotationId,b.annotations[2].annotationId]);assert.deepEqual(W.reviewQueue(n,[{annotationId:n.annotations[1].annotationId,status:'complete'},{annotationId:n.annotations[2].annotationId,status:'unresolved'}]),[n.annotations[2].annotationId]);assert.equal(n.annotations.length,3);});
test('previous and next unresolved navigation is deterministic',()=>{let q=['a','c','f'];assert.equal(W.navigate(q,'c',-1),'a');assert.equal(W.navigate(q,'c',1),'f');assert.equal(W.navigate(q,'a',-1),null);assert.equal(W.navigate(q,'f',1),null);assert.equal(W.navigate(q,'missing',1),'a');});
test('failed frame result is excluded while unresolved result remains queued',()=>{let b=base();b=W.addSelection(b,b.textSnapshot,0,2);b=W.addSelection(b,b.textSnapshot,2,4);assert.deepEqual(W.reviewQueue(b,[{annotationId:b.annotations[1].annotationId,status:'failed'},{annotationId:b.annotations[2].annotationId,status:'unresolved'}]),[b.annotations[2].annotationId]);});
test('empty and out-of-range selections are rejected',()=>{let b=base();assert.throws(()=>W.addSelection(b,b.textSnapshot,1,1),/invalid-source-selection/);assert.throws(()=>W.addSelection(b,b.textSnapshot,-1,2),/invalid-source-selection/);assert.throws(()=>W.addSelection(b,'別文',0,1),/source-snapshot-mismatch/);});
