/* Illustrator boundary for formal Step 1: one horizontal PointText. */
function FormalStep1Adapter(doc, source) {
    var trace=[];
    function mark(stage,detail){trace.push(stage+(detail?":"+detail:""));}
    function check(item){for(var p=item;p&&p.typename!=="Document";p=p.parent)if(p.locked===true||p.hidden===true)throw Error("locked-or-hidden");}
    function snapshot(){if(app.activeDocument!==doc)throw Error("document-changed");check(source);return{text:String(source.contents),note:String(source.note)};}
    function inspect(bundle){var out=[],i,item,tag,b,p;for(i=0;i<doc.textFrames.length;i++){item=doc.textFrames[i];tag=String(item.note);b=FormalStore.read(tag);if(b&&b.sourceFrameId===bundle.sourceFrameId&&item!==source)throw Error("source-id-collision");if(tag.indexOf("formal-step1-output:")===0){p=tag.split(";");if(p.length!==3||p[1]!==bundle.sourceFrameId||p[2]!==bundle.annotation.annotationId)throw Error("output-id-collision");out.push(item);}}if(out.length>1)throw Error("output-id-collision");return out;}
    function store(expected,bundle){if(String(source.note)!==String(expected))throw Error("store-concurrent-change");var next=FormalStore.write(expected,bundle);source.note=next;if(String(source.note)!==next)throw Error("store-readback-mismatch");return next;}
    function observe(){mark("observe:start","kind="+String(source.kind)+",orientation="+String(source.orientation));if(source.kind!==TextType.POINTTEXT||source.orientation!==TextOrientation.HORIZONTAL){mark("observe.measurement","unsupported-shape");return{status:"unresolved",reasons:["pointtext-horizontal-only"]};}var r=source.textRange,c=r.characters,i;mark("observe.character-index","start");if(c.length!==String(source.contents).length||r.end-r.start!==c.length)return{status:"unresolved",reasons:["character-count-mismatch"]};for(i=0;i<c.length;i++)if(String(c[i].contents)!==String(source.contents).charAt(i)||c[i].start!==i||c[i].end!==i+1)return{status:"unresolved",reasons:["character-index-mismatch"]};mark("observe.character-index","complete");if(r.lines.length!==1||r.lines[0].start!==r.start||r.lines[0].end!==r.end){mark("observe.line-map","unverified");return{status:"unresolved",reasons:["line-map-unverified"]};}mark("observe.line-map","complete");var m={left:source.left,top:source.top,width:source.width,baseSize:c[0].characterAttributes.size,fontName:c[0].characterAttributes.textFont.name};mark("observe.measurement","complete");return{status:"complete",metrics:m};}
    function reconcile(bundle,decision){var output=inspect(bundle)[0],d=decision.desired[0],created=false;try{if(!d){mark("render:remove","start");if(output)output.remove();mark("render:remove","complete");return;}if(!output){mark("render:create","start");output=source.layer.textFrames.add();created=true;mark("render:create","complete");}else mark("render:update","start");output.note="formal-step1-output:v1;"+bundle.sourceFrameId+";"+bundle.annotation.annotationId;output.contents=d.reading;output.textRange.characterAttributes.size=d.metrics.baseSize*d.style.sizeRatio;var count=String(d.reading).length,delta=d.metrics.width-output.width,tracking=count>1&&d.metrics.baseSize>0?delta/(d.metrics.baseSize*d.style.sizeRatio*(count-1))*1000:0;if(tracking<-400)tracking=-400;if(tracking>400)tracking=400;if(tracking)mark("render.width-fit","tracking="+tracking);output.textRange.characterAttributes.tracking=tracking;output.left=d.metrics.left+(d.metrics.width-output.width)/2+d.offset.inlineEm*d.metrics.baseSize;output.top=d.metrics.top+output.textRange.characterAttributes.size+d.metrics.baseSize*d.style.gapRatio;mark("render:update","complete");}catch(e){if(created)try{output.remove();}catch(ignore){}throw e;}}
    return{snapshot:snapshot,inspect:inspect,store:store,observe:observe,reconcile:reconcile,diagnostics:function(){return trace.slice();}};
}

/* Pure width helper used by tests and for future renderer extraction. */
function FormalStep1Tracking(sourceWidth, rubyWidth, baseSize, sizeRatio, readingLength) {
    var value=readingLength>1&&baseSize>0?(sourceWidth-rubyWidth)/(baseSize*sizeRatio*(readingLength-1))*1000:0;
    if(value<-400)value=-400;if(value>400)value=400;return value;
}
