/* v2 Formal Step 1: domain and application, independent of Illustrator DOM. */
var FormalStep1 = (function () {
    var seq=0;
    function fail(m){throw Error(m);}
    function id(kind){seq++;return "v2-"+kind+"-"+new Date().getTime()+"-"+seq;}
    function number(v){return typeof v==="number"&&isFinite(v);}
    function valid(v){return typeof v==="string"&&/^v2-[a-z]+-[0-9]+-[0-9]+$/.test(v);}
    function validate(b){var a=b&&b.annotation;if(!b||b.schemaVersion!==1||!number(b.revision)||b.revision<0||typeof b.sourceFrameId!=="string"||typeof b.textSnapshot!=="string"||!a||!valid(a.annotationId)||a.sourceFrameId!==b.sourceFrameId||!a.anchor||typeof a.anchor.baseText!=="string"||!number(a.anchor.startHint)||a.anchor.startHint<0||typeof a.anchor.beforeContext!=="string"||typeof a.anchor.afterContext!=="string"||typeof a.reading!=="string"||typeof a.enabled!=="boolean"||typeof a.readingConfirmed!=="boolean"||!/^(auto|auto_offset|manual)$/.test(a.placementMode)||!(a.reviewReasons instanceof Array)||!a.style||!number(a.style.sizeRatio)||!number(a.style.gapRatio)||!a.offset||!number(a.offset.inlineEm)||!number(a.offset.blockEm)||!/^(complete|pending|unresolved|failed)$/.test(b.renderStatus))fail("invalid-source-bundle");if(b.textSnapshot.substr(a.anchor.startHint,a.anchor.baseText.length)!==a.anchor.baseText)fail("anchor-snapshot-mismatch");return b;}
    function create(text){if(!text)fail("empty-source");var sid=id("source");return validate({schemaVersion:1,revision:0,sourceFrameId:sid,textSnapshot:String(text),renderStatus:"unresolved",annotation:{annotationId:id("annotation"),sourceFrameId:sid,anchor:{baseText:String(text),startHint:0,beforeContext:"",afterContext:""},reading:"",enabled:true,placementMode:"auto",reviewReasons:["reading-unconfirmed"],readingConfirmed:false,style:{sizeRatio:.5,gapRatio:.1},offset:{inlineEm:0,blockEm:0}}});}
    function clone(b){return JSON.parse(JSON.stringify(validate(b)));}
    function resolve(text,snapshot,a){if(text===snapshot)return{status:"complete",start:a.startHint};var hits=[],p=-1;while((p=text.indexOf(a.anchor.baseText,p+1))>=0)if(text.substr(p-a.anchor.beforeContext.length,a.anchor.beforeContext.length)===a.anchor.beforeContext&&text.substr(p+a.anchor.baseText.length,a.anchor.afterContext.length)===a.anchor.afterContext)hits.push(p);return hits.length===1?{status:"complete",start:hits[0]}:{status:"unresolved",reasons:[hits.length?"anchor-ambiguous":"anchor-missing"]};}
    function plan(b,text,observation){var a=b.annotation,reasons=[];if(!a.enabled)return{status:"complete",desired:[]};if(!a.readingConfirmed||!a.reading)reasons.push("reading-unconfirmed");if(a.placementMode==="manual")reasons.push("manual-placement");var r=resolve(text,b.textSnapshot,a);if(r.status!=="complete")reasons=reasons.concat(r.reasons);if(observation.status==="failed")return{status:"failed",reasons:(observation.reasons||["observation-failed"]).concat(reasons)};if(observation.status!=="complete")reasons=reasons.concat(observation.reasons||["observation-unavailable"]);return reasons.length?{status:"unresolved",reasons:reasons}:{status:"complete",desired:[{reading:a.reading,style:a.style,offset:a.offset,metrics:observation.metrics}]};}
    function apply(port,context,edit){var before=port.snapshot(),b=clone(context.bundle),a=b.annotation,observation,decision,trace=[];if(before.text!==context.snapshot.text||before.note!==context.snapshot.note)fail("stale-source");port.inspect(b);a.reading=edit.reading;a.enabled=edit.enabled;a.readingConfirmed=edit.readingConfirmed;a.placementMode=edit.placementMode;a.style=edit.style;a.offset=edit.offset;try{observation=a.enabled?port.observe():{status:"complete"};}catch(e){observation={status:"failed",reasons:["observation-failed:"+(e.message||e)]};}if(port.diagnostics)trace=port.diagnostics();decision=plan(b,before.text,observation);if(trace.length&&decision.status!=="complete")decision.reasons=(decision.reasons||[]).concat(trace);b.revision++;b.annotation.reviewReasons=decision.status==="complete"?[]:decision.reasons;b.renderStatus=decision.status==="complete"?"pending":decision.status;var saved=port.store(before.note,b);if(decision.status!=="complete")return{bundle:b,decision:decision,observation:observation};try{port.reconcile(b,decision);b.renderStatus="complete";}catch(e){b.renderStatus="failed";b.annotation.reviewReasons=["render-failed:"+(e.message||e)].concat(port.diagnostics?port.diagnostics():[]);}port.store(saved,b);return{bundle:b,decision:decision,observation:observation};}
    return{create:create,validate:validate,clone:clone,resolve:resolve,plan:plan,apply:apply};
}());
if(typeof module!=="undefined")module.exports=FormalStep1;
