#target illustrator
#include "../formal-step1/core.js"
#include "../formal-step2/appearance.js"
#include "../formal-step2/multi.js"
#include "../formal-step2/multi-store.js"
#include "../formal-step2/occurrences.js"
#include "../formal-step2/projection.js"
#include "../formal-step2/segments.js"
#include "../formal-step2/orchestration.js"
#include "../formal-step2/multi-renderer.js"
#include "../formal-step2/area-text-native.js"
#include "../formal-step2/area-text-native-store.js"
#include "../formal-step2/area-text-native-note-adapter.js"
#include "../formal-step2/area-text-native-output-identity.js"
#include "../formal-step2/area-text-render-spec.js"
#include "../formal-step2/area-text-native-backend.jsx"
#include "../formal-step2/area-text-native-host.jsx"
#include "../formal-step2/area-text-native-persistence-facade.js"
#include "../formal-step2/area-text-native-transaction-coordinator.js"
#include "../formal-step2/area-text-native-integration.js"

(function () {
    var report = [], doc = null, layer = null, source = null, unmanaged = null, backend = null, sourceId = "native-split-source", candidates = {};
    function fail(message) { throw Error(message); }
    function emit(status, id, detail) { report.push(status + " " + id + (detail ? " | " + detail : "")); }
    function text(value) { return value === undefined || value === null ? "" : String(value); }
    function fontName() { var name = ""; try { name = source.textRange.characterAttributes.textFont.name; } catch (e) {} if (!name) fail("font-unavailable"); return text(name); }
    function policy() { return { justification: "full", singleWordJustification: "full", oneCharacterPolicy: "center", minimumGlyphScaling: 100, desiredGlyphScaling: 100, maximumGlyphScaling: 100, minimumLetterSpacing: null, desiredLetterSpacing: null, maximumLetterSpacing: null, minimumWordSpacing: null, desiredWordSpacing: null, maximumWordSpacing: null, trackingCandidates: [0, -25, -50, -75, -100] }; }
    function spec(id, logicalId, annotationId, reading, name, left, width, requestId) { return FormalAreaTextRenderSpec.create({ sourceFrameId: sourceId, annotationId: annotationId, logicalSegmentId: logicalId, reading: reading, appearance: { fontName: name, fontSize: 8, manualDeltaX: 0, widthScale: 1, gapEm: .15 }, geometry: { autoLeft: left, autoTop: 420, autoWidth: width, boxHeight: 70 }, meta: { requestId: requestId, generationId: "generation-" + id, physicalId: id }, composerPolicy: policy() }); }
    function record(item, observation) { return { physicalId: item.physicalId, sourceFrameId: sourceId, logicalSegmentId: item.logicalSegmentId, generationId: item.generationId, requestId: item.requestId, rendererVersion: item.rendererVersion, geometryVersion: item.geometryVersion, autoLeft: item.geometry.autoLeft, autoWidth: item.geometry.autoWidth, appliedLeft: observation.frameLeft, appliedWidth: observation.textPathWidth !== null ? observation.textPathWidth : observation.frameWidth, appliedTop: observation.frameTop, appliedHeight: observation.textPathHeight !== null ? observation.textPathHeight : observation.frameHeight, tracking: observation.tracking, fontName: observation.fontName, fontSize: observation.fontSize, justification: "full", singleWordJustification: "full", fitReason: "fit-one-line-covered" }; }
    function find(batch, id) { var i; for (i = 0; i < batch.candidates.length; i++) if (batch.candidates[i].spec.physicalId === id) return batch.candidates[i].candidate; return null; }
    function resolve(id) { return FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames, sourceId, id); }
    function dispose(id) { var result = candidates[id] ? backend.disposeCandidate(candidates[id]) : null; if (result && result.cleanupFailed) fail("cleanup-failed-" + id); delete candidates[id]; }
    function cleanup() { var key, ok = true; for (key in candidates) if (Object.prototype.hasOwnProperty.call(candidates, key)) try { dispose(key); } catch (e) { emit("FAIL", "cleanup-" + key, e.message || e); ok = false; } try { if (doc) { doc.close(SaveOptions.DONOTSAVECHANGES); doc = null; } } catch (e2) { emit("FAIL", "cleanup-document", e2.message || e2); ok = false; } if (ok) emit("PASS", "cleanup", "disposable document and owned AreaText removed"); }
    function pureCheckpoint() {
        var base = "一張羅", reading = "いっちょうら", lines2 = [{ start: 0, end: 2, geometry: {} }, { start: 2, end: 3, geometry: {} }], hint = { baseBoundaryAfter: 2, readingBoundaryAfter: 5, baseText: base, reading: reading, baseRevision: 0, readingRevision: 0 }, two = FormalSegments.plan(base, reading, lines2, [hint], 0, 0), one = FormalSegments.plan(base, reading, [{ start: 0, end: 3, geometry: {} }], [hint], 0, 0), back = FormalSegments.plan(base, reading, lines2, [hint], 0, 0), stale = FormalSegments.plan(base, reading, lines2, [{ baseBoundaryAfter: 2, readingBoundaryAfter: 5, baseText: base, reading: "old", baseRevision: 0, readingRevision: 0 }], 0, 0), peerActive = "peer-generation";
        if (two.status !== "complete" || two.segments.length !== 2 || two.segments[0].reading !== "いっちょう" || two.segments[1].reading !== "ら") fail("split-hint-plan-invalid"); emit("PASS", "split-hint-plan", "segments=2;order=0,1;readingBoundary=5"); if (one.status !== "complete" || one.segments.length !== 1 || !one.ignoredHints) fail("reflow-to-one-simulation-invalid"); if (back.status !== "complete" || back.segments.length !== 2) fail("reflow-back-to-two-simulation-invalid"); emit("PASS", "simulated-reflow", "2-to-1-to-2;valid-hint-reused"); if (stale.status !== "unresolved") fail("stale-hint-not-fail-closed"); if (peerActive !== "peer-generation") fail("stale-hint-damaged-peer"); emit("PASS", "stale-hint-peer-safety", "unresolved;peer-state-unchanged"); }
    try {
        var name, logical, frame, projected, annotationId, hint, multiBundle, host, seam, tx, specs, prepared, verified, activation, state, bindings, records, result, ids, i, resolved;
        if (app.documents.length) fail("existing-document-open; refusing-to-touch-user-document");
        pureCheckpoint(); doc = app.documents.add(); layer = doc.layers.add(); backend = FormalAreaTextNativeBackend(doc, layer); source = doc.textFrames.areaText(layer.pathItems.rectangle(600, 100, 420, 180)); source.name = "FormalStep2NativeSplitSource"; source.contents = "一張羅 乙"; source.note = ""; unmanaged = doc.textFrames.add(); unmanaged.name = "FormalStep2NativeSplitUnmanaged"; unmanaged.contents = "keep"; name = fontName();
        logical = FormalLongText.extract(source.contents); logical.occurrences[0].reading = "いっちょうら"; logical.occurrences[0].readingConfirmed = true; logical.occurrences[1].reading = "おつ"; logical.occurrences[1].readingConfirmed = true; frame = FormalMulti.createFrame(source.contents); frame.sourceFrameId = sourceId; frame.occurrences = logical.occurrences; projected = FormalMultiProjection.project(frame); annotationId = projected.annotations[0].annotationId; hint = { baseBoundaryAfter: 2, readingBoundaryAfter: 5, baseText: "一張羅", reading: "いっちょうら", baseRevision: projected.revision, readingRevision: projected.revision }; projected.annotations[0].splitHints = [hint]; FormalMulti.validate(projected); source.note = FormalMultiStore.write(source.note, projected); if (!FormalMultiStore.read(source.note) || FormalMultiStore.read(source.note).annotations[0].splitHints.length !== 1) fail("split-hint-persistence-failed"); emit("PASS", "split-hint-persisted", "baseBoundary=2;readingBoundary=5");
        specs = [spec("split-a1", "split-a-0", annotationId, "いっちょう", name, 120, 90, "split-request-1"), spec("split-a2", "split-a-1", annotationId, "ら", name, 210, 40, "split-request-1"), spec("split-b1", "split-b-0", projected.annotations[1].annotationId, "おつ", name, 300, 60, "split-request-1")]; host = FormalAreaTextNativeHost(doc, layer); seam = FormalAreaTextNativeIntegration.create({ planAll: function () { return { status: "complete" }; } }, host, FormalAreaTextNativeTransactionCoordinator); tx = { source: source, requestId: "split-request-1", expectedContents: source.contents, expectedNote: source.note }; prepared = seam.planAndPrepare({}, source.contents, {}, specs, tx); for (i = 0; i < specs.length; i++) candidates[specs[i].physicalId] = find(prepared.batch, specs[i].physicalId); verified = seam.verify(prepared); activation = seam.activate(source, tx.expectedContents, tx.expectedNote, tx.requestId, verified, [], []); state = FormalAreaTextNativePersistenceFacade.read(source).manifest; ids = ["split-a1", "split-a2", "split-b1"]; for (i = 0; i < ids.length; i++) { resolved = resolve(ids[i]); if (resolved.status !== "found") fail("segment-identity-missing-" + ids[i]); } if (state.activeBindings["split-a-0"] !== "split-a1" || state.activeBindings["split-a-1"] !== "split-a2" || state.activeBindings["split-b-0"] !== "split-b1") fail("segment-bindings-invalid"); emit("PASS", "native-three-segment-activation", "segments=3;uniqueIdentity=true;order=a1,a2,b1"); result = FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, activation.note, tx.requestId); state = result.manifest; if (state.operation !== null || state.activeBindings["split-a-0"] !== "split-a1") fail("native-finish-invalid"); emit("PASS", "native-reconcile-idempotence", "activeBindings stable after finish;no duplicate generation");
        for (i = 0; i < ids.length; i++) dispose(ids[i]); if (source.contents !== "一張羅 乙" || unmanaged.contents !== "keep") fail("source-or-unmanaged-mutated"); if (!FormalMultiStore.read(source.note) || FormalMultiStore.read(source.note).annotations[0].splitHints.length !== 1) fail("split-hint-lost-after-native-persistence"); emit("PASS", "source-unmanaged-preserved", "source=一張羅 乙;splitHint-retained");
    } catch (e) { emit("FAIL", "runtime", e.message || e); }
    cleanup(); $.writeln(report.join("\n")); alert("Formal Step 2 AreaText-native SplitHint checkpoint\n" + report.join("\n"));
}());
