#target illustrator
#include "../formal-step1/core.js"
#include "../formal-step1/store.js"
#include "../formal-step2/appearance.js"
#include "../formal-step2/multi.js"
#include "../formal-step2/multi-store.js"
#include "../formal-step2/occurrences.js"
#include "../formal-step2/projection.js"
#include "../formal-step2/segments.js"
#include "../formal-step2/orchestration.js"
#include "../formal-step2/multi-renderer.js"
#include "../formal-step2/adapter.jsx"
#include "../formal-step2/area-text-native.js"
#include "../formal-step2/area-text-native-store.js"
#include "../formal-step2/area-text-native-note-adapter.js"
#include "../formal-step2/area-text-native-output-identity.js"
#include "../formal-step2/area-text-render-spec.js"
#include "../formal-step2/area-text-native-backend.jsx"
#include "../formal-step2/area-text-native-host.jsx"
#include "../formal-step2/area-text-native-persistence-facade.js"
#include "../formal-step2/area-text-native-transaction-coordinator.js"
#include "../formal-step2/area-text-native-integration.js"

(function () {
    var report = [], doc = null, layer = null, source = null, unmanaged = null, adapter = null, backend = null, host = null, seam = null, sourceId = "native-reflow-source", candidateById = {};
    function fail(message) { throw Error(message); }
    function emit(status, id, detail) { report.push(status + " " + id + (detail ? " | " + detail : "")); }
    function text(value) { return value === undefined || value === null ? "" : String(value); }
    function fontName() { var name = ""; try { name = source.textRange.characterAttributes.textFont.name; } catch (e) {} if (!name) fail("font-unavailable"); return name; }
    function policy() { return { justification: "full", singleWordJustification: "full", oneCharacterPolicy: "center", minimumGlyphScaling: 100, desiredGlyphScaling: 100, maximumGlyphScaling: 100, minimumLetterSpacing: null, desiredLetterSpacing: null, maximumLetterSpacing: null, minimumWordSpacing: null, desiredWordSpacing: null, maximumWordSpacing: null, trackingCandidates: [0, -25, -50, -75, -100] }; }
    function lineDetail(observation) { var out = [], i, line, geometry; if (!observation || !observation.lines) return "lines=unknown"; for (i = 0; i < observation.lines.length; i++) { line = observation.lines[i]; geometry = line.geometry || {}; out.push(i + ":" + line.start + "-" + line.end + ":width=" + text(geometry.measuredWidth || geometry.width) + ":glyphTop=" + text(geometry.measuredTop)); } return "lines=" + observation.lines.length + ";" + out.join(","); }
    function observe(stage) { var result = adapter.observe(); emit(result.status === "complete" ? "PASS" : "MANUAL_REQUIRED", stage, lineDetail(result) + ";diagnostics=" + adapter.diagnostics().join("|")); return result; }
    function spec(id, logicalId, annotationId, reading, name, geometry, requestId) { var width = geometry.measuredWidth || geometry.width; return FormalAreaTextRenderSpec.create({ sourceFrameId: sourceId, annotationId: annotationId, logicalSegmentId: logicalId, reading: reading, appearance: { fontName: name, fontSize: 35, manualDeltaX: 0, widthScale: 1, gapEm: .15 }, geometry: { autoLeft: geometry.left, autoTop: geometry.top, autoWidth: width, boxHeight: Math.max(35, geometry.baseSize || 70) }, meta: { requestId: requestId, generationId: "generation-" + id, physicalId: id }, composerPolicy: policy() }); }
    function specsFor(decision, annotationId, generation, requestId, name) { var result = [], i, segment, logical; for (i = 0; i < decision.segments.length; i++) { segment = decision.segments[i]; logical = "split-" + i; result.push(spec(generation + "-" + i, logical, annotationId, segment.reading, name, segment.geometry, requestId)); } return result; }
    function find(batch, id) { var i; for (i = 0; i < batch.candidates.length; i++) if (batch.candidates[i].spec.physicalId === id) return batch.candidates[i].candidate; return null; }
    function resolve(id) { return FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames, sourceId, id); }
    function dispose(id) { var result = candidateById[id] ? backend.disposeCandidate(candidateById[id]) : null; if (result && result.cleanupFailed) fail("cleanup-failed-" + id); delete candidateById[id]; }
    function nativeBatch(requestId, specs, overrides, retireIds) {
        var tx = { source: source, requestId: requestId, expectedContents: source.contents, expectedNote: source.note }, prepared, verified, bindings, records, activation, i;
        prepared = seam.planAndPrepare({}, source.contents, {}, specs, tx); if (prepared.status !== "prepared") fail("native-reflow-prepare-failed"); for (i = 0; i < specs.length; i++) candidateById[specs[i].physicalId] = find(prepared.batch, specs[i].physicalId); verified = seam.verify(prepared); if (!verified.durableVerify || verified.durableVerify.status !== "success") fail("native-reflow-verify-failed");
        if (overrides) { bindings = host.bindingsByLogicalSegmentId(verified.batch); records = host.recordsByPhysicalId(verified.batch); for (i = 0; i < overrides.length; i++) bindings[overrides[i]] = null; activation = FormalAreaTextNativeTransactionCoordinator.activate(source, tx.expectedContents, tx.expectedNote, tx.requestId, bindings, records, retireIds || [], []); } else activation = seam.activate(source, tx.expectedContents, tx.expectedNote, tx.requestId, verified, retireIds || [], []);
        return { transaction: tx, activation: activation, specs: specs };
    }
    function durableFinish(transaction, activation) { return FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, activation.note, transaction.requestId); }
    function retireAndFinish(requestId, expectedNote, ids) { var retired = FormalAreaTextNativeTransactionCoordinator.retire(source, source.contents, expectedNote, ids); return FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, retired.note, requestId); }
    function cleanupActive() {
        var state = FormalAreaTextNativePersistenceFacade.read(source).manifest, ids = [], logical = [], key, transaction, begun, verified, bindings = {}, activation, i;
        for (key in state.activeBindings) if (Object.prototype.hasOwnProperty.call(state.activeBindings, key)) { logical.push(key); ids.push(state.activeBindings[key]); bindings[key] = null; }
        if (!ids.length) return;
        transaction = { source: source, requestId: "reflow-cleanup", expectedContents: source.contents, expectedNote: source.note }; begun = FormalAreaTextNativeTransactionCoordinator.begin(source, transaction.expectedContents, transaction.expectedNote, transaction.requestId, []); transaction.expectedNote = begun.note; verified = FormalAreaTextNativeTransactionCoordinator.verify(source, transaction.expectedContents, transaction.expectedNote, transaction.requestId); transaction.expectedNote = verified.note; activation = FormalAreaTextNativeTransactionCoordinator.activate(source, transaction.expectedContents, transaction.expectedNote, transaction.requestId, bindings, {}, ids, []); for (i = 0; i < ids.length; i++) dispose(ids[i]); retireAndFinish(transaction.requestId, activation.note, ids); emit("PASS", "owned-output-cleanup", "retired=" + ids.join(",")); }
    function cleanup() {
        try { if (source) cleanupActive(); } catch (e) { emit("FAIL", "owned-output-cleanup", e.message || e); }
        try { if (doc) { doc.close(SaveOptions.DONOTSAVECHANGES); emit("PASS", "disposable-document-cleanup", "closed=true"); } } catch (e2) { emit("FAIL", "disposable-document-cleanup", e2.message || e2); }
    }
    function pureCheckpoint() {
        var base = "一張羅", reading = "いっちょうら", hint = { baseBoundaryAfter: 2, readingBoundaryAfter: 5, baseText: base, reading: reading, baseRevision: 0, readingRevision: 0 }, two = FormalSegments.plan(base, reading, [{ start: 0, end: 2, geometry: {} }, { start: 2, end: 3, geometry: {} }], [hint], 0, 0), one = FormalSegments.plan(base, reading, [{ start: 0, end: 3, geometry: {} }], [hint], 0, 0), back = FormalSegments.plan(base, reading, [{ start: 0, end: 2, geometry: {} }, { start: 2, end: 3, geometry: {} }], [hint], 0, 0), stale = FormalSegments.plan(base, reading, [{ start: 0, end: 2, geometry: {} }, { start: 2, end: 3, geometry: {} }], [{ baseBoundaryAfter: 2, readingBoundaryAfter: 5, baseText: base, reading: "old", baseRevision: 0, readingRevision: 0 }], 0, 0);
        if (two.status !== "complete" || two.segments.length !== 2 || one.status !== "complete" || one.segments.length !== 1 || !one.ignoredHints || back.segments.length !== 2 || stale.status !== "unresolved") fail("pure-reflow-contract-failed"); emit("PASS", "pure-reflow-contract", "2-to-1-to-2;valid-hint-reused;stale-hint-unresolved"); }
    try {
        var name, logical, frame, projected, annotationId, hint, observation, decision, specs, first, firstState, firstIds, wide, wideDecision, wideResult, wideIds, restored, restoredDecision, restoredResult, restoredIds, state, i, multiStored;
        if (app.documents.length) fail("existing-document-open; refusing-to-touch-user-document");
        pureCheckpoint(); doc = app.documents.add(); layer = doc.layers.add(); source = doc.textFrames.areaText(layer.pathItems.rectangle(620, 100, 160, 260)); source.name = "FormalStep2NativeReflowSource"; source.contents = "一張羅"; source.note = ""; source.textRange.characterAttributes.size = 70; unmanaged = doc.textFrames.add(); unmanaged.name = "FormalStep2NativeReflowUnmanaged"; unmanaged.contents = "keep"; adapter = FormalStep2Adapter(doc, source); backend = FormalAreaTextNativeBackend(doc, layer); host = FormalAreaTextNativeHost(doc, layer); seam = FormalAreaTextNativeIntegration.create({ planAll: function () { return { status: "complete" }; } }, host, FormalAreaTextNativeTransactionCoordinator); name = fontName();
        logical = FormalLongText.extract(source.contents); logical.occurrences[0].reading = "いっちょうら"; logical.occurrences[0].readingConfirmed = true; frame = FormalMulti.createFrame(source.contents); frame.sourceFrameId = sourceId; frame.occurrences = logical.occurrences; projected = FormalMultiProjection.project(frame); annotationId = projected.annotations[0].annotationId; hint = { baseBoundaryAfter: 2, readingBoundaryAfter: 5, baseText: source.contents, reading: "いっちょうら", baseRevision: projected.revision, readingRevision: projected.revision }; projected.annotations[0].splitHints = [hint]; FormalMulti.validate(projected); source.note = FormalMultiStore.write(source.note, projected); multiStored = FormalMultiStore.read(source.note); if (!multiStored || multiStored.annotations[0].splitHints.length !== 1) fail("split-hint-store-readback-failed"); emit("PASS", "fixture", "kind=" + source.kind + ";orientation=" + source.orientation + ";fontSize=70");
        observation = observe("initial-observe"); if (observation.status !== "complete" || observation.lines.length !== 2) { emit("MANUAL_REQUIRED", "initial-two-line", lineDetail(observation)); throw Error("initial-two-line-not-established"); }
        decision = FormalSegments.plan(source.contents, "いっちょうら", observation.lines, [hint], 0, 0); if (decision.status !== "complete" || decision.segments.length !== 2) fail("initial-two-segment-plan-failed"); specs = specsFor(decision, annotationId, "split-g1", "reflow-request-1", name); first = nativeBatch("reflow-request-1", specs, null, []); firstState = FormalAreaTextNativePersistenceFacade.read(source).manifest; firstIds = [specs[0].physicalId, specs[1].physicalId]; for (i = 0; i < firstIds.length; i++) if (resolve(firstIds[i]).status !== "found") fail("initial-segment-missing-" + i); if (firstState.activeBindings["split-0"] !== firstIds[0] || firstState.activeBindings["split-1"] !== firstIds[1]) fail("initial-segment-bindings-invalid"); durableFinish(first.transaction, first.activation); emit("PASS", "initial-two-segment-activation", "segments=2;ids=" + firstIds.join(","));
        var textPath = null, originalTextPathWidth = null; try { textPath = source.textPath; originalTextPathWidth = textPath && textPath.width; } catch (pathError) { emit("MANUAL_REQUIRED", "textPath-snapshot", pathError.message || pathError); }
        if (!textPath || typeof originalTextPathWidth !== "number") { emit("MANUAL_REQUIRED", "actual-reflow", "textPath width unavailable"); cleanupActive(); throw Error("actual-reflow-unavailable"); }
        textPath.width = originalTextPathWidth * 4; app.redraw(); wide = observe("widen-observe"); wideDecision = wide.status === "complete" ? FormalSegments.plan(source.contents, "いっちょうら", wide.lines, [hint], 0, 0) : null; if (!wideDecision || wide.lines.length !== 1) { emit("MANUAL_REQUIRED", "actual-2-to-1-reflow", lineDetail(wide) + ";textPathWidth=" + textPath.width); textPath.width = originalTextPathWidth; app.redraw(); restored = observe("restore-observe"); cleanupActive(); if (source.contents !== "一張羅" || unmanaged.contents !== "keep") fail("source-or-unmanaged-mutated"); emit("PASS", "source-unmanaged-preserved", "reflow-unproven;source-restored"); throw Error("actual-reflow-manual-required"); }
        if (wideDecision.status !== "complete" || wideDecision.segments.length !== 1) fail("actual-one-line-plan-failed"); wideResult = nativeBatch("reflow-request-2", specsFor(wideDecision, annotationId, "split-g2", "reflow-request-2", name), ["split-1"], firstIds); wideIds = [wideResult.specs[0].physicalId]; state = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (state.activeBindings["split-0"] !== wideIds[0] || state.activeBindings["split-1"] !== undefined || state.retirementQueue.length !== 2) fail("actual-one-line-activation-invalid"); for (i = 0; i < firstIds.length; i++) dispose(firstIds[i]); retireAndFinish(wideResult.transaction.requestId, wideResult.activation.note, firstIds); emit("PASS", "actual-2-to-1", lineDetail(wide) + ";segments=1;persistedHintIgnored=true");
        textPath.width = originalTextPathWidth; app.redraw(); restored = observe("narrow-observe"); if (restored.status !== "complete" || restored.lines.length !== 2) { emit("MANUAL_REQUIRED", "actual-1-to-2-reflow", lineDetail(restored)); cleanupActive(); throw Error("actual-return-to-two-lines-unproven"); }
        restoredDecision = FormalSegments.plan(source.contents, "いっちょうら", restored.lines, [hint], 0, 0); if (restoredDecision.status !== "complete" || restoredDecision.segments.length !== 2) fail("restored-split-hint-plan-failed"); restoredResult = nativeBatch("reflow-request-3", specsFor(restoredDecision, annotationId, "split-g3", "reflow-request-3", name), null, wideIds); restoredIds = [restoredResult.specs[0].physicalId, restoredResult.specs[1].physicalId]; state = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (state.activeBindings["split-0"] !== restoredIds[0] || state.activeBindings["split-1"] !== restoredIds[1]) fail("restored-two-segment-bindings-invalid"); dispose(wideIds[0]); retireAndFinish(restoredResult.transaction.requestId, restoredResult.activation.note, wideIds); emit("PASS", "actual-1-to-2", lineDetail(restored) + ";segments=2;validHintReused=true");
        cleanupActive(); multiStored = FormalMultiStore.read(source.note); if (!multiStored || multiStored.annotations[0].splitHints.length !== 1) fail("final-split-hint-lost"); if (source.contents !== "一張羅" || unmanaged.contents !== "keep") fail("source-or-unmanaged-mutated"); emit("PASS", "source-unmanaged-preserved", "source=一張羅;splitHint-retained");
    } catch (e) { if (e.message !== "actual-reflow-manual-required" && e.message !== "actual-reflow-unavailable" && e.message !== "actual-return-to-two-lines-unproven" && e.message !== "initial-two-line-not-established") emit("FAIL", "runtime", e.message || e); }
    cleanup(); $.writeln(report.join("\n")); alert("Formal Step 2 AreaText-native reflow checkpoint\n" + report.join("\n"));
}());
