#target illustrator
#include "../formal-step1/core.js"
#include "../formal-step2/appearance.js"
#include "../formal-step2/multi.js"
#include "../formal-step2/occurrences.js"
#include "../formal-step2/projection.js"
#include "../formal-step2/segments.js"
#include "../formal-step2/orchestration.js"
#include "../formal-step2/multi-renderer.js"
#include "../formal-step2/area-text-native.js"
#include "../formal-step2/area-text-native-store.js"
#include "../formal-step2/area-text-native-note-adapter.js"
#include "../formal-step2/area-text-native-output-identity.js"
#include "../formal-step2/area-text-render-spec.js"
#include "../formal-step2/area-text-native-backend.jsx"
#include "../formal-step2/area-text-native-host.jsx"
#include "../formal-step2/area-text-native-persistence-facade.js"
#include "../formal-step2/area-text-native-transaction-coordinator.js"
#include "../formal-step2/area-text-native-integration.js"

(function () {
    var report = [], doc = null, layer = null, source = null, unmanaged = null, backend = null, sourceId = "native-multi-source", candidates = {};
    function fail(message) { throw Error(message); }
    function emit(status, id, detail) { report.push(status + " " + id + (detail ? " | " + detail : "")); }
    function text(value) { return value === undefined || value === null ? "" : String(value); }
    function fontName() { var name = ""; try { name = source.textRange.characterAttributes.textFont.name; } catch (e) {} if (!name) fail("font-unavailable"); return text(name); }
    function policy() { return { justification: "full", singleWordJustification: "full", oneCharacterPolicy: "center", minimumGlyphScaling: 100, desiredGlyphScaling: 100, maximumGlyphScaling: 100, minimumLetterSpacing: null, desiredLetterSpacing: null, maximumLetterSpacing: null, minimumWordSpacing: null, desiredWordSpacing: null, maximumWordSpacing: null, trackingCandidates: [0, -25, -50, -75, -100] }; }
    function spec(id, logicalId, reading, name, left, requestId) {
        return FormalAreaTextRenderSpec.create({ sourceFrameId: sourceId, annotationId: logicalId, logicalSegmentId: logicalId, reading: reading, appearance: { fontName: name, fontSize: 8, manualDeltaX: 0, widthScale: 1, gapEm: .15 }, geometry: { autoLeft: left, autoTop: 420, autoWidth: 90, boxHeight: 70 }, meta: { requestId: requestId, generationId: "generation-" + id, physicalId: id }, composerPolicy: policy() });
    }
    function record(item, observation) {
        return { physicalId: item.physicalId, sourceFrameId: sourceId, logicalSegmentId: item.logicalSegmentId, generationId: item.generationId, requestId: item.requestId, rendererVersion: item.rendererVersion, geometryVersion: item.geometryVersion, autoLeft: item.geometry.autoLeft, autoWidth: item.geometry.autoWidth, appliedLeft: observation.frameLeft, appliedWidth: observation.textPathWidth !== null ? observation.textPathWidth : observation.frameWidth, appliedTop: observation.frameTop, appliedHeight: observation.textPathHeight !== null ? observation.textPathHeight : observation.frameHeight, tracking: observation.tracking, fontName: observation.fontName, fontSize: observation.fontSize, justification: "full", singleWordJustification: "full", fitReason: "fit-one-line-covered" };
    }
    function find(batch, id) { var i; for (i = 0; i < batch.candidates.length; i++) if (batch.candidates[i].spec.physicalId === id) return batch.candidates[i].candidate; return null; }
    function resolve(id) { return FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames, sourceId, id); }
    function dispose(id) { var result = candidates[id] ? backend.disposeCandidate(candidates[id]) : null; if (result && result.cleanupFailed) fail("cleanup-failed-" + id); delete candidates[id]; }
    function cleanup() { var key, ok = true; for (key in candidates) if (Object.prototype.hasOwnProperty.call(candidates, key)) try { dispose(key); } catch (e) { emit("FAIL", "cleanup-" + key, e.message || e); ok = false; } try { if (doc) { doc.close(SaveOptions.DONOTSAVECHANGES); doc = null; } } catch (e2) { emit("FAIL", "cleanup-document", e2.message || e2); ok = false; } if (ok) emit("PASS", "cleanup", "disposable document and owned AreaText removed"); }
    function pureCheckpoint() {
        var logical = FormalLongText.extract("甲 乙"), frame = FormalMulti.createFrame(logical.textSnapshot), projected, a, b, rendererCalls = [], observation = { status: "complete", lines: [{ start: 0, end: 1, geometry: { left: 0, top: 0, width: 20, charWidths: [20] } }, { start: 2, end: 3, geometry: { left: 30, top: 0, width: 20, charWidths: [20] } }] }, plan, suppressed, next;
        logical.occurrences[0].reading = "こう"; logical.occurrences[0].readingConfirmed = true; logical.occurrences[1].reading = "おつ"; logical.occurrences[1].readingConfirmed = true; frame.occurrences = logical.occurrences; projected = FormalMultiProjection.project(frame); a = projected.annotations[0].annotationId; b = projected.annotations[1].annotationId; plan = FormalMultiRenderer.plan(projected, projected.textSnapshot, observation); if (plan.status !== "complete" || plan.plans.length !== 2 || plan.plans[0].annotationId !== a || plan.plans[1].annotationId !== b) fail("multi-order-not-deterministic"); FormalMultiRenderer.render(projected, projected.textSnapshot, observation, { reconcile: function (bundle, decision) { rendererCalls.push({ id: bundle.annotation.annotationId, count: decision.segments.length }); } }); if (rendererCalls.length !== 2 || rendererCalls[0].id !== a || rendererCalls[1].id !== b) fail("multi-render-order-invalid"); emit("PASS", "pure-order", "two annotations planned and rendered in source order"); suppressed = FormalMulti.clone(projected); suppressed.occurrences[0].enabled = false; next = FormalMultiProjection.project(FormalMulti.replaceOccurrences(suppressed, suppressed.occurrences)); plan = FormalMultiRenderer.plan(next, next.textSnapshot, observation); if (plan.status !== "complete" || plan.plans.length !== 2 || !plan.plans[0].suppressed || plan.plans[1].annotationId !== b) fail("suppression-damaged-peer"); emit("PASS", "pure-suppress-peer", "annotation A suppressed; annotation B remains renderable"); }
    try {
        var name, logical, frame, projected, aid, bid, host, seam, tx, first, firstResult, second, secondResult, firstA, firstB, secondB, state, bindings, records, finish, oldA, oldB;
        if (app.documents.length) fail("existing-document-open; refusing-to-touch-user-document");
        pureCheckpoint();
        doc = app.documents.add(); layer = doc.layers.add(); backend = FormalAreaTextNativeBackend(doc, layer); source = doc.textFrames.areaText(layer.pathItems.rectangle(600, 100, 420, 180)); source.name = "FormalStep2NativeMultiSource"; source.contents = "甲 乙"; source.note = ""; unmanaged = doc.textFrames.add(); unmanaged.name = "FormalStep2NativeMultiUnmanaged"; unmanaged.contents = "keep"; name = fontName();
        logical = FormalLongText.extract(source.contents); logical.occurrences[0].reading = "こう"; logical.occurrences[0].readingConfirmed = true; logical.occurrences[1].reading = "おつ"; logical.occurrences[1].readingConfirmed = true; frame = FormalMulti.createFrame(source.contents); frame.sourceFrameId = sourceId; frame.occurrences = logical.occurrences; projected = FormalMultiProjection.project(frame); aid = projected.annotations[0].annotationId; bid = projected.annotations[1].annotationId; emit("PASS", "fixture", "kind=" + source.kind + ";orientation=" + source.orientation + ";annotations=2");
        host = FormalAreaTextNativeHost(doc, layer); seam = FormalAreaTextNativeIntegration.create({ planAll: function () { return { status: "complete" }; } }, host, FormalAreaTextNativeTransactionCoordinator);
        first = [spec("multi-a-g1", aid, "こう", name, 120, "multi-request-1"), spec("multi-b-g1", bid, "おつ", name, 270, "multi-request-1")]; tx = { source: source, requestId: "multi-request-1", expectedContents: source.contents, expectedNote: source.note }; firstResult = seam.planAndPrepare({}, source.contents, {}, first, tx); candidates[first[0].physicalId] = find(firstResult.batch, first[0].physicalId); candidates[first[1].physicalId] = find(firstResult.batch, first[1].physicalId); if (firstResult.status !== "prepared" || firstResult.durableBegin.status !== "success") fail("first-begin-failed"); firstResult = seam.verify(firstResult); if (firstResult.durableVerify.status !== "success") fail("first-verify-failed"); firstResult = seam.activate(source, tx.expectedContents, tx.expectedNote, tx.requestId, firstResult, [], []); state = FormalAreaTextNativePersistenceFacade.read(source).manifest; firstA = resolve(first[0].physicalId); firstB = resolve(first[1].physicalId); if (state.activeBindings[aid] !== first[0].physicalId || state.activeBindings[bid] !== first[1].physicalId || firstA.status !== "found" || firstB.status !== "found") fail("multi-active-bindings-invalid"); emit("PASS", "create-two-managed", "A=" + firstA.status + ";B=" + firstB.status + ";activeBindings=2"); finish = FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, firstResult.note, tx.requestId); tx.expectedNote = finish.note; emit("PASS", "first-finish", "manifestRevision=" + finish.manifest.manifestRevision);
        second = [spec("multi-b-g2", bid, "おつづけ", name, 270, "multi-request-2")]; tx.requestId = "multi-request-2"; tx.expectedNote = source.note; secondResult = seam.planAndPrepare({}, source.contents, {}, second, tx); candidates[second[0].physicalId] = find(secondResult.batch, second[0].physicalId); secondResult = seam.verify(secondResult); bindings = host.bindingsByLogicalSegmentId(secondResult.batch); records = host.recordsByPhysicalId(secondResult.batch); bindings[aid] = null; secondResult = FormalAreaTextNativeTransactionCoordinator.activate(source, tx.expectedContents, tx.expectedNote, tx.requestId, bindings, records, [first[0].physicalId, first[1].physicalId], []); state = FormalAreaTextNativePersistenceFacade.read(source).manifest; oldA = resolve(first[0].physicalId); oldB = resolve(first[1].physicalId); secondB = resolve(second[0].physicalId); if (state.activeBindings[aid] !== undefined || state.activeBindings[bid] !== second[0].physicalId || oldA.status !== "found" || oldB.status !== "found" || secondB.status !== "found") fail("single-edit-or-suppression-invalid"); emit("PASS", "suppress-a-edit-b", "A=inactive;B=multi-b-g2;oldOutputsStillPresent=true"); dispose(first[0].physicalId); dispose(first[1].physicalId); finish = FormalAreaTextNativeTransactionCoordinator.retire(source, source.contents, secondResult.note, [first[0].physicalId, first[1].physicalId]); finish = FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, finish.note, tx.requestId); state = finish.manifest; if (state.activeBindings[bid] !== second[0].physicalId || state.retirementQueue.length !== 0 || state.operation !== null) fail("manifest-final-state-invalid"); emit("PASS", "manifest-authority", "active B only;retirementQueue=0;operation=null");
        if (source.contents !== "甲 乙" || unmanaged.contents !== "keep") fail("source-or-unmanaged-mutated"); emit("PASS", "source-unmanaged-preserved", "source=甲 乙;unmanaged=keep");
    } catch (e) { emit("FAIL", "runtime", e.message || e); }
    cleanup(); $.writeln(report.join("\n")); alert("Formal Step 2 AreaText-native multi-annotation checkpoint\n" + report.join("\n"));
}());
