#target illustrator
#include "../formal-step2/area-text-native.js"
#include "../formal-step2/area-text-native-store.js"
#include "../formal-step2/area-text-native-note-adapter.js"
#include "../formal-step2/area-text-native-output-identity.js"
#include "../formal-step2/area-text-render-spec.js"
#include "../formal-step2/area-text-native-backend.jsx"
#include "../formal-step2/area-text-native-host.jsx"
#include "../formal-step2/area-text-native-persistence-facade.js"
#include "../formal-step2/area-text-native-transaction-coordinator.js"
#include "../formal-step2/area-text-native-integration.js"

(function () {
    var report = [], doc = null, layer = null, source = null, unmanaged = null, backend = null, sourceId = "native-integration-source", candidates = {};

    function text(value) { return value === undefined || value === null ? "" : String(value); }
    function fail(message) { throw Error(message); }
    function emit(status, caseId, detail) { report.push(status + " " + caseId + (detail ? " | " + detail : "")); }
    function finite(value, name) { if (typeof value !== "number" || !isFinite(value)) fail(name + "-nonfinite"); return value; }
    function sourceFontName() { var name = ""; try { name = source.textRange.characterAttributes.textFont.name; } catch (e) {} if (!name) fail("source-font-unavailable"); return text(name); }
    function composerPolicy() { return { justification: "full", singleWordJustification: "full", oneCharacterPolicy: "center", minimumGlyphScaling: 100, desiredGlyphScaling: 100, maximumGlyphScaling: 100, minimumLetterSpacing: null, desiredLetterSpacing: null, maximumLetterSpacing: null, minimumWordSpacing: null, desiredWordSpacing: null, maximumWordSpacing: null, trackingCandidates: [0, -25, -50, -75, -100] }; }
    function renderSpec(id, logicalId, requestId, fontName, left) {
        return FormalAreaTextRenderSpec.create({ sourceFrameId: sourceId, annotationId: "integration-annotation", logicalSegmentId: logicalId, reading: "いっちょうら", appearance: { fontName: fontName, fontSize: 8, manualDeltaX: 0, widthScale: 1, gapEm: .15 }, geometry: { autoLeft: left, autoTop: 420, autoWidth: 220, boxHeight: 80 }, meta: { requestId: requestId, generationId: "generation-" + id, physicalId: id }, composerPolicy: composerPolicy() });
    }
    function record(spec, observation) {
        return { physicalId: spec.physicalId, sourceFrameId: sourceId, logicalSegmentId: spec.logicalSegmentId, generationId: spec.generationId, requestId: spec.requestId, rendererVersion: spec.rendererVersion, geometryVersion: spec.geometryVersion, autoLeft: spec.geometry.autoLeft, autoWidth: spec.geometry.autoWidth, appliedLeft: finite(observation.frameLeft, "applied-left"), appliedWidth: finite(observation.textPathWidth !== null ? observation.textPathWidth : observation.frameWidth, "applied-width"), appliedTop: finite(observation.frameTop, "applied-top"), appliedHeight: finite(observation.textPathHeight !== null ? observation.textPathHeight : observation.frameHeight, "applied-height"), tracking: finite(observation.tracking, "tracking"), fontName: text(observation.fontName), fontSize: finite(observation.fontSize, "font-size"), justification: "full", singleWordJustification: "full", fitReason: "fit-one-line-covered" };
    }
    function resolver() { return function (frameId, physicalId) { return FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames, frameId, physicalId); }; }
    function findCandidate(batch, physicalId) { var i; for (i = 0; i < batch.candidates.length; i++) if (batch.candidates[i].spec.physicalId === physicalId) return batch.candidates[i].candidate; return null; }
    function retainCandidate(batch, physicalId) { var kept = [], records = [], i; for (i = 0; i < batch.candidates.length; i++) if (batch.candidates[i].spec.physicalId === physicalId) kept.push(batch.candidates[i]); for (i = 0; i < batch.records.length; i++) if (batch.records[i].physicalId === physicalId) records.push(batch.records[i]); batch.candidates = kept; batch.records = records; }
    function dispose(id) { var result = candidates[id] ? backend.disposeCandidate(candidates[id]) : null; if (result && result.cleanupFailed) fail("cleanup-failed-" + id); if (candidates[id]) delete candidates[id]; }
    function cleanup() { var ok = true, key; for (key in candidates) if (Object.prototype.hasOwnProperty.call(candidates, key)) try { dispose(key); } catch (e) { emit("FAIL", "cleanup-" + key, e.message || e); ok = false; } try { if (doc) { doc.close(SaveOptions.DONOTSAVECHANGES); doc = null; } } catch (e2) { emit("FAIL", "cleanup-document", e2.message || e2); ok = false; } if (ok) emit("PASS", "cleanup", "disposable document and owned candidates removed"); }
    try {
        var fontName, oldSpec, oldCandidate, oldObservation, manifest, newSpecs, host, seam, transaction, prepared, verified, discardedCandidate, activation, state, retired, cleaned, finished, beforeOld, afterOld, afterNew, afterDiscarded;
        if (app.documents.length) fail("existing-document-open; refusing to touch user document");
        doc = app.documents.add(); layer = doc.layers.add(); backend = FormalAreaTextNativeBackend(doc, layer); source = doc.textFrames.areaText(layer.pathItems.rectangle(600, 100, 420, 180)); source.name = "FormalStep2NativeIntegrationSource"; source.contents = "一張羅"; unmanaged = doc.textFrames.add(); unmanaged.name = "FormalStep2NativeIntegrationUnmanaged"; unmanaged.contents = "unmanaged"; fontName = sourceFontName();
        oldSpec = renderSpec("old", "segment", "seed-request", fontName, 120); oldCandidate = backend.prepareCandidate(FormalAreaTextRenderSpec.backendSpec(oldSpec)); candidates.old = oldCandidate; oldObservation = backend.stableObservation ? backend.stableObservation(oldCandidate) : backend.observeCandidate(oldCandidate); manifest = FormalAreaTextNative.createManifest(); manifest.activeBindings.segment = "old"; manifest.renderRecords.old = record(oldSpec, oldObservation); FormalAreaTextNativeNoteAdapter.update(source, source.note, manifest); emit("PASS", "seed-old-active", "active=old;kind=" + source.kind + ";orientation=" + source.orientation);
        newSpecs = [renderSpec("new", "segment", "integration-request", fontName, 120), renderSpec("discarded", "discarded", "integration-request", fontName, 360)]; host = FormalAreaTextNativeHost(doc, layer); seam = FormalAreaTextNativeIntegration.create({ planAll: function () { return { status: "complete" }; } }, host, FormalAreaTextNativeTransactionCoordinator); transaction = { source: source, requestId: "integration-request", expectedContents: source.contents, expectedNote: source.note }; prepared = seam.planAndPrepare({}, source.contents, {}, newSpecs, transaction); candidates.created = findCandidate(prepared.batch, "new"); candidates.discarded = findCandidate(prepared.batch, "discarded"); if (!prepared.durableBegin || prepared.durableBegin.status !== "success") fail("durable-begin-not-persisted"); state = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (!state.operation || state.operation.phase !== "prepare") fail("begin-phase-not-prepare"); emit("PASS", "durable-begin", "phase=" + state.operation.phase + ";candidateCount=" + state.operation.candidateIds.length); emit("PASS", "candidate-prepared", "new=" + (candidates.created ? "yes" : "no") + ";discarded=" + (candidates.discarded ? "yes" : "no"));
        verified = seam.verify(prepared); if (!verified.durableVerify || verified.durableVerify.status !== "success") fail("durable-verify-not-persisted"); state = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (!state.operation || state.operation.phase !== "verified") fail("verify-phase-not-persisted"); emit("PASS", "host-verified", "candidates=" + verified.batch.candidates.length); emit("PASS", "durable-verified", "phase=" + state.operation.phase);
        beforeOld = resolver()(sourceId, "old"); if (beforeOld.status !== "found") fail("old-active-missing-before-activation"); emit("PASS", "old-active-before-activation", "status=" + beforeOld.status);
        discardedCandidate = candidates.discarded; retainCandidate(verified.batch, "new"); activation = seam.activate(source, transaction.expectedContents, transaction.expectedNote, transaction.requestId, verified, ["old"], ["discarded"]); state = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (state.activeBindings.segment !== "new") fail("new-active-not-persisted"); if (state.retirementQueue.length !== 1 || state.retirementQueue[0] !== "old") fail("old-retirement-not-queued"); if (state.cleanupQueue.length !== 1 || state.cleanupQueue[0] !== "discarded") fail("discarded-cleanup-not-queued"); emit("PASS", "activated-new-active", "active=" + state.activeBindings.segment + ";revision=" + state.manifestRevision); afterOld = resolver()(sourceId, "old"); afterNew = resolver()(sourceId, "new"); afterDiscarded = resolver()(sourceId, "discarded"); if (afterOld.status !== "found" || afterNew.status !== "found" || afterDiscarded.status !== "found") fail("post-activation-object-missing"); emit("PASS", "retirement-and-cleanup-pending", "old=" + afterOld.status + ";discarded=" + afterDiscarded.status);
        dispose("old"); dispose("discarded"); retired = FormalAreaTextNativeTransactionCoordinator.retire(source, source.contents, activation.note, ["old"]); cleaned = FormalAreaTextNativeTransactionCoordinator.cleanupDiscarded(source, source.contents, retired.note, ["discarded"]); if (cleaned.restartPlan.action !== "finish-operation") fail("cleanup-restart-plan-unexpected"); finished = FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, cleaned.note, transaction.requestId); if (finished.manifest.operation !== null) fail("operation-not-finished"); emit("PASS", "cleanup-success", "restartPlan=" + finished.restartPlan.action);
        if (source.contents !== "一張羅") fail("source-content-mutated"); if (!unmanaged.parent) fail("unmanaged-object-lost"); emit("PASS", "source-and-unmanaged-preserved", "sourceContents=" + source.contents);
    } catch (e) { emit("FAIL", "runtime", e.message || e); }
    cleanup(); $.writeln(report.join("\n")); alert("Formal Step 2 AreaText-native integration checkpoint\n" + report.join("\n"));
}());
