#target illustrator
#include "../formal-step1/core.js"
#include "../formal-step2/multi.js"
#include "../formal-step2/multi-store.js"
#include "../formal-step2/orchestration.js"
#include "../formal-step2/occurrences.js"
#include "../formal-step2/projection.js"
#include "../formal-step2/segments.js"
#include "../formal-step2/area-text-native.js"
#include "../formal-step2/area-text-native-store.js"
#include "../formal-step2/area-text-native-note-adapter.js"
#include "../formal-step2/area-text-native-output-identity.js"
#include "../formal-step2/area-text-render-spec.js"
#include "../formal-step2/area-text-native-backend.jsx"
#include "../formal-step2/area-text-native-host.jsx"
#include "../formal-step2/area-text-native-persistence-facade.js"
#include "../formal-step2/area-text-native-transaction-coordinator.js"
#include "../formal-step2/area-text-native-integration.js"

(function () {
    var report = [], doc = null, reopened = null, layer = null, source = null, backend = null, tempFile = null;
    var sourceId = "native-persistence-ownership-source", unmanagedName = "NativePersistenceOwnership-Unmanaged";
    var candidates = {};
    function text(v) { return v === undefined || v === null ? "" : String(v); }
    function emit(s, id, d) { report.push(s + " " + id + (d ? " | " + d : "")); }
    function fail(m) { throw Error(m); }
    function fontName() { var n = ""; try { n = text(source.textRange.characterAttributes.textFont.name); } catch (e) {} if (!n) fail("font-unavailable"); return n; }
    function policy() { return { justification: "full", singleWordJustification: "full", oneCharacterPolicy: "center", minimumGlyphScaling: 100, desiredGlyphScaling: 100, maximumGlyphScaling: 100, minimumLetterSpacing: null, desiredLetterSpacing: null, maximumLetterSpacing: null, minimumWordSpacing: null, desiredWordSpacing: null, maximumWordSpacing: null, trackingCandidates: [0, -25, -50, -75, -100] }; }
    function spec(id, logical, annotation, reading, left, width, request, font) { return FormalAreaTextRenderSpec.create({ sourceFrameId: sourceId, annotationId: annotation, logicalSegmentId: logical, reading: reading, appearance: { fontName: font, fontSize: 8, manualDeltaX: 0, widthScale: 1, gapEm: .15 }, geometry: { autoLeft: left, autoTop: 420, autoWidth: width, boxHeight: 70 }, meta: { requestId: request, generationId: "generation-" + id, physicalId: id }, composerPolicy: policy() }); }
    function find(batch, id) { var i; for (i = 0; i < batch.candidates.length; i++) if (batch.candidates[i].spec.physicalId === id) return batch.candidates[i].candidate; return null; }
    function resolve(id, target) { return FormalAreaTextNativeOutputIdentity.resolve((target || doc).textFrames, sourceId, id); }
    function dispose(id) { if (candidates[id]) { backend.disposeCandidate(candidates[id]); delete candidates[id]; } }
    function removeOwned(id, target) { var found = resolve(id, target); if (found.status === "found") { found.frame.remove(); return true; } return false; }
    function managedInventory(target) { var out = [], i, identity; for (i = 0; i < target.textFrames.length; i++) { identity = FormalAreaTextNativeOutputIdentity.parse(text(target.textFrames[i].note)); if (identity && identity.sourceFrameId === sourceId) out.push(identity.physicalId); } return out; }
    function assertOwnership(target, manifest, expectedCount) { var seen = {}, states = {}, inventory, i, logical, physical, record, pending, retired; if (manifest.operation !== null) fail("reopened-operation-not-finished"); for (logical in manifest.activeBindings) if (Object.prototype.hasOwnProperty.call(manifest.activeBindings, logical)) { physical = manifest.activeBindings[logical]; if (seen[physical] || states[physical]) fail("duplicate-physical-ownership"); seen[physical] = true; states[physical] = "active"; record = manifest.renderRecords[physical]; if (!record || record.physicalId !== physical || record.logicalSegmentId !== logical) fail("active-record-bijection-failed"); if (resolve(physical, target).status !== "found") fail("active-physical-missing"); } pending = manifest.operation && manifest.operation.candidateIds || []; for (i = 0; i < pending.length; i++) { if (states[pending[i]]) fail("pending-active-ownership-overlap"); states[pending[i]] = "pending"; } retired = manifest.retirementQueue || []; for (i = 0; i < retired.length; i++) { if (states[retired[i]]) fail("retirement-active-ownership-overlap"); states[retired[i]] = "retirement"; } if ((manifest.cleanupQueue || []).length) fail("finished-reopen-cleanup-pending"); inventory = managedInventory(target); if (inventory.length !== expectedCount) fail("managed-frame-inventory-mismatch;expected=" + expectedCount + ";actual=" + inventory.length + ";physicalIds=" + inventory.join(",")); }
    function stageBatch(request, specs) { var host = FormalAreaTextNativeHost(doc, layer), seam = FormalAreaTextNativeIntegration.create({ planAll: function () { return { status: "complete" }; } }, host, FormalAreaTextNativeTransactionCoordinator), tx = { source: source, requestId: request, expectedContents: source.contents, expectedNote: source.note }, prepared, i; prepared = seam.planAndPrepare({}, source.contents, {}, specs, tx); if (prepared.status !== "prepared") fail("prepare-failed"); for (i = 0; i < specs.length; i++) candidates[specs[i].physicalId] = find(prepared.batch, specs[i].physicalId); return { host: host, seam: seam, tx: tx, prepared: prepared }; }
    function verifyStaged(ctx) { var verified = ctx.seam.verify(ctx.prepared); if (!verified.durableVerify || verified.durableVerify.status !== "success") fail("verify-failed"); ctx.verified = verified; return verified; }
    function activateVerified(ctx, retireIds, removedLogicalSegmentIds) { if (!removedLogicalSegmentIds && retireIds && retireIds.length === 2 && retireIds[1] === "persist-a2") removedLogicalSegmentIds = ["persist-a-1"]; ctx.activation = ctx.seam.activate(source, ctx.tx.expectedContents, ctx.tx.expectedNote, ctx.tx.requestId, ctx.verified, retireIds || [], [], removedLogicalSegmentIds || []); return ctx.activation; }
    function finishActivated(ctx) { ctx.finished = FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, ctx.activation.note, ctx.tx.requestId); return ctx.finished; }
    function activateStaged(ctx, retireIds) { verifyStaged(ctx); activateVerified(ctx, retireIds); finishActivated(ctx); return ctx.activation; }
    function activateBatch(request, specs, retireIds) { return activateStaged(stageBatch(request, specs), retireIds); }
    function findSource(target) { var i; for (i = 0; i < target.textFrames.length; i++) if (text(target.textFrames[i].name) === "FormalStep2NativePersistenceOwnershipSource") return target.textFrames[i]; return null; }
    function cleanup() { var k, ok = true; for (k in candidates) if (Object.prototype.hasOwnProperty.call(candidates, k)) try { dispose(k); } catch (e) { ok = false; emit("FAIL", "cleanup-owned", e.message || e); } try { if (reopened) reopened.close(SaveOptions.DONOTSAVECHANGES); if (doc) doc.close(SaveOptions.DONOTSAVECHANGES); } catch (e2) { ok = false; emit("FAIL", "cleanup-document", e2.message || e2); } if (tempFile) try { if (tempFile.exists) ok = tempFile.remove() && ok; } catch (e3) { ok = false; emit("FAIL", "cleanup-file", e3.message || e3); } if (ok) emit("PASS", "cleanup", "disposable document and temporary file removed"); }
    try {
        var name, unmanaged, logical, frame, projected, a, b, hint, multi, initialSpecs, ids, i, state, activeBefore, activeAfter, reopenedState, oldId = "persist-a1", newId = "persist-a1-r2";
        if (app.documents.length) fail("existing-document-open; refusing-to-touch-user-document");
        doc = app.documents.add(); layer = doc.layers.add(); source = doc.textFrames.areaText(layer.pathItems.rectangle(620, 100, 420, 180)); source.name = "FormalStep2NativePersistenceOwnershipSource"; source.contents = "一張羅 甲乙"; source.note = ""; unmanaged = doc.textFrames.add(); unmanaged.name = unmanagedName; unmanaged.contents = "keep"; backend = FormalAreaTextNativeBackend(doc, layer); name = fontName();
        logical = FormalLongText.extract(source.contents); logical.occurrences[0].reading = "いっちょうら"; logical.occurrences[0].readingConfirmed = true; logical.occurrences[1].reading = "こうおつ"; logical.occurrences[1].readingConfirmed = true; frame = FormalMulti.createFrame(source.contents); frame.sourceFrameId = sourceId; frame.occurrences = logical.occurrences; projected = FormalMultiProjection.project(frame); a = projected.annotations[0].annotationId; b = projected.annotations[1].annotationId; hint = { baseBoundaryAfter: 2, readingBoundaryAfter: 5, baseText: "一張羅", reading: "いっちょうら", baseRevision: projected.revision, readingRevision: projected.revision }; projected.annotations[0].splitHints = [hint]; FormalMulti.validate(projected); source.note = FormalMultiStore.write(source.note, projected); multi = FormalMultiStore.read(source.note); if (!multi || multi.annotations.length !== 2 || multi.annotations[0].splitHints.length !== 1) fail("multi-split-hint-persist-failed"); emit("PASS", "fixture", "annotations=2;splitHint=2,5;source-and-unmanaged-created");
        initialSpecs = [spec(oldId, "persist-a-0", a, "いっちょう", 120, 120, "persist-r1", name), spec("persist-a2", "persist-a-1", a, "ら", 240, 60, "persist-r1", name), spec("persist-b1", "persist-b-0", b, "こうおつ", 320, 120, "persist-r1", name)]; activateBatch("persist-r1", initialSpecs, []); ids = [oldId, "persist-a2", "persist-b1"]; for (i = 0; i < ids.length; i++) if (resolve(ids[i]).status !== "found") fail("initial-active-missing-" + ids[i]); emit("PASS", "initial-activation", "active annotations=2;managed segments=3");
        tempFile = new File(Folder.temp.fsName + "/FormalStep2NativePersistenceOwnership-" + String((new Date()).getTime()) + ".ai"); doc.saveAs(tempFile); doc.close(SaveOptions.DONOTSAVECHANGES); doc = null; candidates = {}; reopened = app.open(tempFile); source = findSource(reopened); if (!source) fail("reopened-source-missing"); state = FormalAreaTextNativePersistenceFacade.read(source); if (!state.manifest || state.manifest.operation !== null) fail("reopened-manifest-not-finished"); multi = FormalMultiStore.read(source.note); if (!multi || multi.annotations.length !== 2 || multi.annotations[0].reading !== "いっちょうら" || !multi.annotations[0].readingConfirmed || multi.annotations[1].reading !== "こうおつ" || !multi.annotations[1].readingConfirmed) fail("reopened-reading-state-invalid"); if (multi.annotations[0].splitHints.length !== 1 || multi.annotations[0].splitHints[0].baseBoundaryAfter !== 2 || multi.annotations[0].splitHints[0].readingBoundaryAfter !== 5 || multi.annotations[0].splitHints[0].baseText !== "一張羅" || multi.annotations[0].splitHints[0].reading !== "いっちょうら" || multi.annotations[0].splitHints[0].baseRevision !== multi.revision || multi.annotations[0].splitHints[0].readingRevision !== multi.revision) fail("reopened-splithint-invalid"); for (i = 0; i < ids.length; i++) if (resolve(ids[i], reopened).status !== "found") fail("reopened-active-missing-" + ids[i]); assertOwnership(reopened, state.manifest, 3); if (text(source.contents) !== "一張羅 甲乙") fail("source-contents-changed"); unmanaged = null; for (i = 0; i < reopened.textFrames.length; i++) if (text(reopened.textFrames[i].name) === unmanagedName) unmanaged = reopened.textFrames[i]; if (!unmanaged || text(unmanaged.contents) !== "keep") fail("unmanaged-changed"); emit("PASS", "save-close-reopen", "readings,SplitHint fields,manifest bijection,3 active outputs,source,unmanaged restored");
        activeBefore = FormalAreaTextNativeStore.serialize(state.manifest); var persistedObservation = { status: "complete", lines: [{ start: 0, end: 2, geometry: { left: 120, top: 420, width: 120 } }, { start: 2, end: 3, geometry: { left: 240, top: 420, width: 60 } }, { start: 3, end: 4, geometry: { left: 300, top: 420, width: 20 } }, { start: 4, end: 6, geometry: { left: 320, top: 420, width: 120 } }] }; var reconcileSeam = FormalAreaTextNativeIntegration.create({ planAll: FormalMultiOrchestration.planAll }, FormalAreaTextNativeHost(reopened, reopened.layers[0]), FormalAreaTextNativeTransactionCoordinator), persistedReconcile = reconcileSeam.reconcileExisting(multi, source.contents, persistedObservation, state.manifest); if (!persistedReconcile || persistedReconcile.status !== "reused" || persistedReconcile.physicalIds.length !== 3) fail("reconcile-seam-not-reused"); state = FormalAreaTextNativePersistenceFacade.read(source); activeAfter = FormalAreaTextNativeStore.serialize(state.manifest); if (activeBefore !== activeAfter || managedInventory(reopened).length !== 3) fail("reconcile-created-duplicate"); emit("PASS", "reconcile-after-reopen", "integration seam reused active physicalIds=" + persistedReconcile.physicalIds.join(",") + ";managedIds=3->3");
        multi = FormalMulti.update(multi, a, { reading: "いちうら", readingConfirmed: true, splitHints: [{ baseBoundaryAfter: 2, readingBoundaryAfter: 2, baseText: "一張羅", reading: "いちうら", baseRevision: multi.revision, readingRevision: multi.revision }] }); source.note = FormalMultiStore.write(source.note, multi); if (FormalMultiStore.read(source.note).annotations[0].reading !== "いちうら" || FormalMultiStore.read(source.note).annotations[0].splitHints[0].readingBoundaryAfter !== 2) fail("reedit-reading-not-persisted"); if (resolve(oldId, reopened).status !== "found") fail("old-active-lost-before-activation"); emit("PASS", "reedit-staging", "changed reading and SplitHint persisted;old active remains before prepare");
        doc = reopened; reopened = null; layer = doc.layers[0]; backend = FormalAreaTextNativeBackend(doc, layer); var staged = stageBatch("persist-r2", [spec(newId, "persist-a-0", a, "いちうら", 120, 180, "persist-r2", name)]), stagedState = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (stagedState.activeBindings["persist-a-0"] !== oldId || resolve(oldId).status !== "found" || stagedState.operation.candidateIds.length !== 1 || stagedState.operation.candidateIds[0] !== newId || resolve(newId).status !== "found") fail("copy-on-write-staging-invalid"); emit("PASS", "copy-on-write-staging", "new candidate prepared;old active remains authoritative;new candidate pending only"); verifyStaged(staged); stagedState = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (stagedState.operation.phase !== "verified" || stagedState.activeBindings["persist-a-0"] !== oldId || !stagedState.operation.candidateIds.length) fail("copy-on-write-verify-boundary-invalid"); emit("PASS", "copy-on-write-verified", "durable verify complete;old active still authoritative"); activateVerified(staged, [oldId, "persist-a2"]); stagedState = FormalAreaTextNativePersistenceFacade.read(source).manifest; if (stagedState.activeBindings["persist-a-0"] !== newId || stagedState.retirementQueue.indexOf(oldId) < 0 || stagedState.retirementQueue.indexOf("persist-a2") < 0) fail("copy-on-write-activation-boundary-invalid"); emit("PASS", "copy-on-write-activated", "new active authoritative;old generation in retirement queue"); finishActivated(staged); state = FormalAreaTextNativePersistenceFacade.read(source); if (state.manifest.operation !== null || state.manifest.activeBindings["persist-a-0"] !== newId || state.manifest.activeBindings["persist-b-0"] !== "persist-b1") fail("copy-on-write-binding-invalid"); emit("PASS", "copy-on-write-after-reopen", "new active survives;peer preserved;finished state consistent"); if (!removeOwned(oldId, doc) || !removeOwned("persist-a2", doc)) fail("old-generation-cleanup-missing"); emit("PASS", "retirement-cleanup", "owned old generation removed only after activation and finish");
    } catch (e) { emit("FAIL", "runtime", e.message || e); }
    cleanup(); $.writeln(report.join("\n")); alert("Formal Step 2 AreaText-native persistence ownership checkpoint\n" + report.join("\n"));
}());
