#target illustrator
#include "../formal-step2/area-text-native.js"
#include "../formal-step2/area-text-native-store.js"
#include "../formal-step2/area-text-native-note-adapter.js"
#include "../formal-step2/area-text-native-output-identity.js"
#include "../formal-step2/area-text-native-backend.jsx"
#include "../formal-step2/area-text-native-persistence-facade.js"
#include "../formal-step2/area-text-native-transaction-coordinator.js"
#include "../formal-step2/area-text-native-recovery.js"

(function () {
    var report = [], doc = null, reopened = null, tempFile = null, layer = null, source = null, sourcePath = null, backend = null, sourceId = "native-lifecycle-source", candidateById = {};
    function text(value) { return value === undefined || value === null ? "" : String(value); }
    function emit(status, stage, detail) { report.push(status + " " + stage + (detail ? " | " + detail : "")); }
    function fail(message) { throw Error(message); }
    function frameSpec(id, left, top) { return { sourceFrameId: sourceId, physicalId: id, logicalSegmentId: id, generationId: "diag-" + id, requestId: "native-lifecycle", rendererVersion: "native-v1", geometryVersion: "geometry-v1", reading: "いっちょうら", left: left, top: top, width: 220, height: 80, singleCharacter: false, appearance: { fontSize: 8 }, composerPolicy: { justification: "full", singleWordJustification: "full", minimumGlyphScaling: 100, desiredGlyphScaling: 100, maximumGlyphScaling: 100, minimumLetterSpacing: 0, desiredLetterSpacing: 0, maximumLetterSpacing: 0, minimumWordSpacing: 80, desiredWordSpacing: 100, maximumWordSpacing: 120, trackingCandidates: [0] } }; }
    function record(id, spec, observation, requestId) { return { physicalId: id, sourceFrameId: sourceId, logicalSegmentId: spec.logicalSegmentId, generationId: spec.generationId, requestId: requestId, rendererVersion: spec.rendererVersion, geometryVersion: spec.geometryVersion, autoLeft: spec.left, autoWidth: spec.width, appliedLeft: observation.frameLeft, appliedWidth: observation.textPathWidth !== null ? observation.textPathWidth : observation.frameWidth, appliedTop: observation.frameTop, appliedHeight: observation.textPathHeight !== null ? observation.textPathHeight : observation.frameHeight, tracking: observation.tracking, fontName: observation.fontName || "", fontSize: observation.fontSize, justification: "full", singleWordJustification: "full", fitReason: "fit-one-line-covered", evidence: { source: "native-lifecycle" } }; }
    function makeSource() { var path = layer.pathItems.rectangle(500, 100, 320, 120), frame = doc.textFrames.areaText(path); frame.name = "FormalStep2NativeLifecycleSource"; frame.contents = "一張羅"; return frame; }
    function inventoryResolver() { return function (frameId, physicalId) { return FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames, frameId, physicalId); }; }
    function materialize(found, missing, reverify, left) { var entries = [], i, id, spec, candidate; for (i = 0; i < found.length; i++) { id = found[i]; candidate = candidateById[id]; if (!candidate) fail("found-candidate-not-materialized:" + id); entries.push({ id: id, candidate: candidate, spec: candidate.spec }); } for (i = 0; i < missing.length; i++) { id = missing[i]; spec = frameSpec(id, left, 400 - i * 100); spec.requestId = "native-lifecycle"; candidate = backend.prepareCandidate(spec); candidateById[id] = candidate; entries.push({ id: id, candidate: candidate, spec: spec }); } return entries; }
    function runExecute(state, requestId, resolver, left, expectedReverify, allowVerifyWrite, forceVerificationFailure) { var prepared, verifyWrites = 0, result = FormalAreaTextNativeRecovery.execute(state, sourceId, requestId, resolver, function (found, missing, reverify) { prepared = { entries: materialize(found, missing, reverify, left), records: {} }; return { entries: prepared.entries, bindings: { main: prepared.entries[prepared.entries.length - 1].id }, records: prepared.records }; }, function (entries, reverify) { var i, observed, checked, item; if (reverify !== expectedReverify) fail("restart-phase-mismatch"); if (forceVerificationFailure) return false; for (i = 0; i < entries.length; i++) { item = entries[i]; checked = backend.verifyCandidate(item.candidate, item.spec); if (!checked.ok) return false; observed = checked.observation; prepared.records[item.id] = record(item.id, item.spec, observed, requestId); } return true; }, function (current, id) { verifyWrites++; if (!allowVerifyWrite) fail("unexpected-verify-write"); return FormalAreaTextNativeTransactionCoordinator.verify(source, source.contents, source.note, id).manifest; }, function (current, id, bindings, records, retireIds, discardedIds) { var activated = FormalAreaTextNativeTransactionCoordinator.activate(source, source.contents, source.note, id, bindings, records, retireIds, discardedIds); if (activated.manifest.operation.phase !== "activated") fail("activation-not-persisted"); return activated; }); return { result: result, verifyWrites: verifyWrites, prepared: prepared }; }
    function dispose(id) { var result = candidateById[id] ? backend.disposeCandidate(candidateById[id]) : null; if (result && result.cleanupFailed) fail("candidate-cleanup-failed:" + id); if (candidateById[id]) delete candidateById[id]; return result; }
    function closeAndReopen() { tempFile = new File(Folder.temp.fsName + "/FormalStep2NativeLifecycle-" + String((new Date()).getTime()) + ".ai"); doc.saveAs(tempFile); doc.close(SaveOptions.DONOTSAVECHANGES); doc = null; reopened = app.open(tempFile); source = null; var i, item; for (i = 0; i < reopened.textFrames.length; i++) { item = reopened.textFrames[i]; if (text(item.name) === "FormalStep2NativeLifecycleSource") { source = item; break; } } if (!source) fail("reopened-source-missing"); }
    function cleanup() { var ok = true; try { if (reopened) { reopened.close(SaveOptions.DONOTSAVECHANGES); reopened = null; } if (doc) { doc.close(SaveOptions.DONOTSAVECHANGES); doc = null; } } catch (e) { emit("FAIL", "cleanup-close", e.message || e); ok = false; } if (tempFile) try { if (tempFile.exists) ok = tempFile.remove() && ok; } catch (e2) { emit("FAIL", "cleanup-file", e2.message || e2); ok = false; } if (ok) emit("PASS", "cleanup", "disposable document and temporary file removed"); }
    try {
        var initial, oldSpec, oldCandidate, prepared, resolved, finalState, duplicate, oldResult, reopenedState, resolver;
        if (app.documents.length) fail("existing-document-open; refusing to touch user document");
        doc = app.documents.add(); layer = doc.layers.add(); source = makeSource(); backend = FormalAreaTextNativeBackend(doc, layer); resolver = inventoryResolver();
        oldSpec = frameSpec("old", 120, 400); oldSpec.requestId = "old-generation"; oldCandidate = backend.prepareCandidate(oldSpec); candidateById.old = oldCandidate;
        initial = FormalAreaTextNative.createManifest(); initial.activeBindings.main = "old"; initial.renderRecords.old = record("old", oldSpec, backend.observeCandidate(oldCandidate), "old-generation"); FormalAreaTextNativeNoteAdapter.update(source, source.note, initial);
        var begun = FormalAreaTextNativeTransactionCoordinator.begin(source, source.contents, source.note, "r1", ["new-1"]); var prepareRestart = FormalAreaTextNativeRecovery.restart(begun.manifest, sourceId, resolver); if (prepareRestart.action !== "prepare-candidates") fail("prepare-restart-not-classified"); emit("PASS", "prepare-restart", "found=" + prepareRestart.found.length + ";missing=" + prepareRestart.missing.length);
        prepared = runExecute(begun.manifest, "r1", resolver, 120, false, true); if (prepared.verifyWrites !== 1) fail("prepare-verify-write-count"); finalState = prepared.result.manifest; emit("PASS", "prepare-activate", "revision=" + finalState.manifestRevision + ";active=" + finalState.activeBindings.main);
        resolved = resolver(sourceId, "old"); if (resolved.status !== "found") fail("retirement-old-not-found"); oldResult = dispose("old"); if (!oldResult || oldResult.cleanupFailed) fail("retirement-cleanup-failed"); var retired = FormalAreaTextNativeTransactionCoordinator.retire(source, source.contents, source.note, ["old"]); var finished = FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, retired.note, "r1"); emit("PASS", "retirement-finish", "restartPlan=" + finished.restartPlan.action);
        var begun2 = FormalAreaTextNativeTransactionCoordinator.begin(source, source.contents, source.note, "r2", ["new-2"]); var verified2 = FormalAreaTextNativeTransactionCoordinator.verify(source, source.contents, begun2.note, "r2"); var verifiedRestart = FormalAreaTextNativeRecovery.restart(verified2.manifest, sourceId, resolver); if (verifiedRestart.action !== "reverify-candidates") fail("verified-restart-not-classified"); emit("PASS", "verified-restart", "found=" + verifiedRestart.found.length + ";missing=" + verifiedRestart.missing.length);
        var failedNote = source.note; var failMap = resolver; var failure = false; try { runExecute(verified2.manifest, "r2", failMap, 340, true, false, true); } catch (failureError) { failure = true; } if (!failure || source.note !== failedNote) fail("verified-failure-mutated-state"); emit("PASS", "verification-failure", "persisted verified state unchanged");
        var resumed2 = runExecute(verified2.manifest, "r2", resolver, 340, true, false); finalState = resumed2.result.manifest; emit("PASS", "verified-activate", "revision=" + finalState.manifestRevision + ";active=" + finalState.activeBindings.main); resolved = resolver(sourceId, "new-1"); if (resolved.status === "found") { dispose("new-1"); } var retired2 = FormalAreaTextNativeTransactionCoordinator.retire(source, source.contents, resumed2.result.note, ["new-1"]); var finished2 = FormalAreaTextNativeTransactionCoordinator.finish(source, source.contents, retired2.note, "r2"); emit("PASS", "second-retirement-finish", "restartPlan=" + finished2.restartPlan.action);
        duplicate = backend.prepareCandidate(frameSpec("new-2", 600, 400)); try { FormalAreaTextNativeRecovery.validateOperationCandidates(sourceId, { operation: { candidateIds: ["new-2"] } }, inventoryResolver()); fail("duplicate-resolver-not-rejected"); } catch (duplicateError) { if (String(duplicateError.message || duplicateError).indexOf("native-recovery-duplicate-candidate") < 0) throw duplicateError; emit("PASS", "duplicate-fail-closed", duplicateError.message || duplicateError); } try { backend.disposeCandidate(duplicate); } catch (ignoreDuplicate) {}
        closeAndReopen(); reopenedState = FormalAreaTextNativePersistenceFacade.read(source); if (!reopenedState.manifest || reopenedState.manifest.operation !== null) fail("reopen-manifest-not-finished"); resolved = FormalAreaTextNativeOutputIdentity.resolve(reopened.textFrames, sourceId, "new-2"); if (resolved.status !== "found") fail("reopen-active-output-missing"); emit("PASS", "save-close-reopen", "active new-2 resolves uniquely");
        emit("PASS", "final-state", "manifestRevision=" + reopenedState.manifest.manifestRevision + ";active=" + reopenedState.manifest.activeBindings.main);
    } catch (e) { emit("FAIL", "runtime", e.message || e); }
    cleanup(); $.writeln(report.join("\n")); alert("Formal Step 2 AreaText-native lifecycle checkpoint\n" + report.join("\n"));
}());
