/* Minimal area-text adapter using observed line geometry. */
function FormalStep2Adapter(doc,source){
 var trace=[];function mark(s,d){trace.push(s+(d?":"+d:""));}
 function snapshot(){if(app.activeDocument!==doc)throw Error("document-changed");return{text:String(source.contents),note:String(source.note)};}
 function inspect(b){var out=[],i,p,x,t;for(i=0;i<doc.textFrames.length;i++){t=doc.textFrames[i];p=String(t.note);if(p.indexOf("formal-step2-output:v1;")===0){x=p.split(";");if(x.length!==4||x[1]!==b.sourceFrameId||x[2]!==b.annotation.annotationId)throw Error("output-id-collision");out.push(t);}}return out;}
 function store(expected,b){if(String(source.note)!==String(expected))throw Error("store-concurrent-change");var n=FormalStep2Store.write(expected,b);source.note=n;if(String(source.note)!==n)throw Error("store-readback-mismatch");return n;}
 function observe(){mark("observe:start","kind="+String(source.kind)+",orientation="+String(source.orientation));if(source.kind!==TextType.AREATEXT||source.orientation!==TextOrientation.HORIZONTAL)return{status:"unresolved",reasons:["area-text-horizontal-only"]};var r=source.textRange,lines=[],i,l;for(i=0;i<r.lines.length;i++){l=r.lines[i];if(typeof l.left!=="number"||typeof l.top!=="number"||typeof l.width!=="number")return{status:"unresolved",reasons:["line-geometry-unavailable"]};lines.push({start:l.start-r.start,end:l.end-r.start,geometry:{left:l.left,top:l.top,width:l.width,baseSize:l.characters[0].characterAttributes.size}});}mark("observe.line-map","complete");return{status:"complete",lines:lines};}
 function reconcile(b,d){var old=inspect(b),wanted=d.segments||[],i,item,g,count,delta,tracking;for(i=old.length-1;i>=wanted.length;i--)old[i].remove();for(i=0;i<wanted.length;i++){item=old[i]||source.layer.textFrames.add();g=wanted[i].geometry;if(!g)throw Error("segment-geometry-unavailable");item.note="formal-step2-output:v1;"+b.sourceFrameId+";"+b.annotation.annotationId+";"+wanted[i].renderSegmentId;item.contents=wanted[i].reading;item.textRange.characterAttributes.size=g.baseSize*.5;count=String(wanted[i].reading).length;delta=g.width-item.width;tracking=count>1&&g.baseSize>0?delta/(g.baseSize*.5*(count-1))*1000:0;if(tracking<-400)tracking=-400;if(tracking>400)tracking=400;item.textRange.characterAttributes.tracking=tracking;if(tracking)mark("render.width-fit","tracking="+tracking);item.left=g.left+(g.width-item.width)/2;item.top=g.top;}mark("render:update","complete");}
 return{snapshot:snapshot,inspect:inspect,store:store,observe:observe,reconcile:reconcile,diagnostics:function(){return trace.slice();}};
}
