/* Separate namespace for the frame-level multi-annotation contract. */
var FormalMultiStore = (function () {
    var open = "[v2-formal-step2-multi:v1]\n", close = "\n[/v2-formal-step2-multi]", fieldSep = "\u0002", hintSep = "\u0003", hintFieldSep = "\u0004";
    function fail(message) { throw Error(message); }
    function locate(note) { var s=String(note), i=s.indexOf(open), e; if(i<0){if(s.indexOf("[v2-formal-step2-multi:")>=0)fail("unknown-multi-store-version");return null;} if(s.indexOf(open,i+1)>=0)fail("duplicate-multi-store"); e=s.indexOf(close,i+open.length); if(e<0)fail("broken-multi-store"); return {start:i,end:e+close.length,payload:s.substring(i+open.length,e)}; }
    function annotationFields(a) { var h=a.anchor; return [a.annotationId,a.sourceFrameId,h.baseText,h.startHint,h.beforeContext,h.afterContext,a.reading,a.enabled,a.placementMode,a.reviewReasons.join("\u0001"),a.readingConfirmed,a.style.sizeRatio,a.style.gapRatio,a.offset.inlineEm,a.offset.blockEm,(a.splitHints||[]).map(function(x){return [x.baseBoundaryAfter,x.readingBoundaryAfter,x.baseText,x.reading,x.baseRevision,x.readingRevision].join(hintFieldSep);}).join(hintSep)].map(encodeURIComponent).join(fieldSep); }
    function parseAnnotation(line, sourceId) { var p=line.split(fieldSep), a, hs, q, i; if(p.length!==16)fail("invalid-multi-annotation"); for(i=0;i<p.length;i++)p[i]=decodeURIComponent(p[i]); if(p[7]!=="true"&&p[7]!=="false")fail("invalid-multi-boolean"); if(p[10]!=="true"&&p[10]!=="false")fail("invalid-multi-boolean"); a={annotationId:p[0],sourceFrameId:p[1],anchor:{baseText:p[2],startHint:Number(p[3]),beforeContext:p[4],afterContext:p[5]},reading:p[6],enabled:p[7]==="true",placementMode:p[8],reviewReasons:p[9]?p[9].split("\u0001"):[],readingConfirmed:p[10]==="true",style:{sizeRatio:Number(p[11]),gapRatio:Number(p[12])},offset:{inlineEm:Number(p[13]),blockEm:Number(p[14])},splitHints:[]}; if(p[15]){hs=p[15].split(hintSep);for(i=0;i<hs.length;i++){q=hs[i].split(hintFieldSep);if(q.length!==6)fail("invalid-multi-split-hint");a.splitHints.push({baseBoundaryAfter:Number(q[0]),readingBoundaryAfter:Number(q[1]),baseText:q[2],reading:q[3],baseRevision:Number(q[4]),readingRevision:Number(q[5])});}} if(a.sourceFrameId!==sourceId)fail("multi-source-frame-mismatch"); return a; }
    function read(note) { var x=locate(note), lines, values={}, seen={}, annotations=[], i, p, key, required=["schemaVersion","revision","sourceFrameId","textSnapshot","renderStatus"]; if(!x)return null; lines=x.payload.split("\n"); for(i=0;i<lines.length;i++){p=lines[i].indexOf("=");if(p<1)fail("invalid-multi-field");key=lines[i].substring(0,p);if(seen[key])fail("duplicate-multi-field");seen[key]=true;if(key.indexOf("annotation.")===0){if(key!=="annotation."+annotations.length)fail("invalid-multi-field");annotations.push(parseAnnotation(decodeURIComponent(lines[i].substring(p+1)),values.sourceFrameId));}else if(required.indexOf(key)>=0)values[key]=decodeURIComponent(lines[i].substring(p+1));else fail("invalid-multi-field");} for(i=0;i<required.length;i++)if(!seen[required[i]])fail("missing-multi-field"); if(values.schemaVersion!=="1")fail("invalid-multi-schema"); if(!annotations.length)fail("invalid-multi-annotations"); return FormalMulti.validate({schemaVersion:Number(values.schemaVersion),revision:Number(values.revision),sourceFrameId:values.sourceFrameId,textSnapshot:values.textSnapshot,renderStatus:values.renderStatus,annotations:annotations}); }
    function write(note,bundle) { FormalMulti.validate(bundle); var lines=["schemaVersion=1","revision="+encodeURIComponent(bundle.revision),"sourceFrameId="+encodeURIComponent(bundle.sourceFrameId),"textSnapshot="+encodeURIComponent(bundle.textSnapshot),"renderStatus="+encodeURIComponent(bundle.renderStatus)], i, x=locate(note), s=String(note), block; for(i=0;i<bundle.annotations.length;i++)lines.push("annotation."+i+"="+encodeURIComponent(annotationFields(bundle.annotations[i]))); block=open+lines.join("\n")+close; return x?s.substring(0,x.start)+block+s.substring(x.end):s+block; }
    return {read:read,write:write};
}());
if(typeof module!=="undefined")module.exports=FormalMultiStore;
