/* Separate namespace for the frame-level multi-annotation contract. */
var FormalMultiStore=(function(){
    var open="[v2-formal-step2-multi:v1]\n", close="\n[/v2-formal-step2-multi]", fieldSep="\u0002", hintSep="\u0003", hintFieldSep="\u0004";
    function locate(note){var s=String(note),i=s.indexOf(open),e;if(i<0){if(s.indexOf("[v2-formal-step2-multi:")>=0)throw Error("unknown-multi-store-version");return null;}if(s.indexOf(open,i+1)>=0)throw Error("duplicate-multi-store");e=s.indexOf(close,i+open.length);if(e<0)throw Error("broken-multi-store");return{start:i,end:e+close.length,payload:s.substring(i+open.length,e)};}
    function fields(a){var h=a.anchor;return [a.annotationId,a.sourceFrameId,h.baseText,h.startHint,h.beforeContext,h.afterContext,a.reading,a.enabled,a.placementMode,a.reviewReasons.join("\u0001"),a.readingConfirmed,a.style.sizeRatio,a.style.gapRatio,a.offset.inlineEm,a.offset.blockEm,(a.splitHints||[]).map(function(x){return [x.baseBoundaryAfter,x.readingBoundaryAfter,x.baseText,x.reading,x.baseRevision,x.readingRevision].join(hintFieldSep);}).join(hintSep)].map(encodeURIComponent).join(fieldSep);}
    function parse(line,sourceId){var p=line.split(fieldSep),a,hints,i,q;if(p.length!==16)throw Error("invalid-multi-annotation");p=p.map(decodeURIComponent);a={annotationId:p[0],sourceFrameId:p[1],anchor:{baseText:p[2],startHint:Number(p[3]),beforeContext:p[4],afterContext:p[5]},reading:p[6],enabled:p[7]==="true",placementMode:p[8],reviewReasons:p[9]?p[9].split("\u0001"):[],readingConfirmed:p[10]==="true",style:{sizeRatio:Number(p[11]),gapRatio:Number(p[12])},offset:{inlineEm:Number(p[13]),blockEm:Number(p[14])},splitHints:[]};if(p[15]){hints=p[15].split(hintSep);for(i=0;i<hints.length;i++){q=hints[i].split(hintFieldSep);if(q.length!==6)throw Error("invalid-multi-split-hint");a.splitHints.push({baseBoundaryAfter:Number(q[0]),readingBoundaryAfter:Number(q[1]),baseText:q[2],reading:q[3],baseRevision:Number(q[4]),readingRevision:Number(q[5])});}}if(a.sourceFrameId!==sourceId)throw Error("multi-source-frame-mismatch");return a;}
    function read(note){var x=locate(note), lines,p,b,i,annotations=[];if(!x)return null;lines=x.payload.split("\n");for(i=0;i<lines.length;i++){p=lines[i].indexOf("=");if(p<1)throw Error("invalid-multi-field");b=lines[i].substring(0,p);if(i===0&&b!=="schemaVersion")throw Error("invalid-multi-field");if(b==="schemaVersion")schema=Number(decodeURIComponent(lines[i].substring(p+1)));else if(b==="revision")revision=Number(decodeURIComponent(lines[i].substring(p+1)));else if(b==="sourceFrameId")sourceId=decodeURIComponent(lines[i].substring(p+1));else if(b==="textSnapshot")text=decodeURIComponent(lines[i].substring(p+1));else if(b==="renderStatus")status=decodeURIComponent(lines[i].substring(p+1));else if(b.indexOf("annotation.")===0)annotations.push(parse(decodeURIComponent(lines[i].substring(p+1)),sourceId));else throw Error("invalid-multi-field");}var bundle={schemaVersion:schema,revision:revision,sourceFrameId:sourceId,textSnapshot:text,renderStatus:status,annotations:annotations};return FormalMulti.validate(bundle);}
    function write(note,bundle){FormalMulti.validate(bundle);var lines=["schemaVersion=1","revision="+encodeURIComponent(bundle.revision),"sourceFrameId="+encodeURIComponent(bundle.sourceFrameId),"textSnapshot="+encodeURIComponent(bundle.textSnapshot),"renderStatus="+encodeURIComponent(bundle.renderStatus)],i;for(i=0;i<bundle.annotations.length;i++)lines.push("annotation."+i+"="+encodeURIComponent(fields(bundle.annotations[i])));var block=open+lines.join("\n")+close,x=locate(note),s=String(note);return x?s.substring(0,x.start)+block+s.substring(x.end):s+block;}
    return{read:read,write:write};
}());
if(typeof module!=="undefined")module.exports=FormalMultiStore;
