/* Persistence bridge for palette callbacks. Serialization stays outside DOM strategy attempts. */
var FormalMultiPersistenceAdapter = (function () {
    var activeMessages=[];
    function errorText(error) { return error && error.message ? error.message : String(error); }
    function encoded(value) { return encodeURIComponent(String(value)); }
    function captureIdentity(source, documentRef) {
        var identity={uuid:null,documentPath:null};
        try { if(source && source.uuid) identity.uuid=String(source.uuid); } catch(error) {}
        try { if(documentRef && documentRef.fullName && documentRef.fullName.fsName) identity.documentPath=String(documentRef.fullName.fsName); } catch(error) {}
        return identity;
    }
    function removeMessage(bt) { for(var i=activeMessages.length-1;i>=0;i--) if(activeMessages[i]===bt) activeMessages.splice(i,1); }
    function verifyStagePath(stagePath, requestId) {
        var stageFile;
        if (!stagePath) throw Error("stage-path-required");
        if (typeof File === "undefined") throw Error("stage-file-unavailable");
        stageFile = File(stagePath);
        if (!stageFile.open("w")) throw Error("stage-file-not-writable");
        try { stageFile.write("formal-multi-host:request-" + requestId + ":pre-send"); } finally { stageFile.close(); }
        return stagePath;
    }
    function verifyRuntimeSources(sources) {
        var names=["step1","segments","orchestration","appearance","multi","multiStore","projection","multiRenderer","nativeRenderer","renderSpec","nativeCore","nativeStore","nativeNoteAdapter","nativePersistence","nativeCoordinator","nativeIdentity","nativeBackend","nativeHost","nativeIntegration","nativeRecovery","nativeRecoveryRuntime","adapter"],i,file;
        if(!sources) throw Error("runtime-sources-required");
        if(typeof File === "undefined") throw Error("runtime-source-file-unavailable");
        for(i=0;i<names.length;i++) { if(!sources[names[i]]) throw Error("runtime-source-path-missing:"+names[i]); file=File(sources[names[i]]); if(!file.exists) throw Error("runtime-source-not-found:"+names[i]); }
        return sources;
    }
    function bridgeBody(expectedText, cachedNote, nextNote, identity) {
        return "(function(){" +
            "function fail(m){throw Error(m);}" +
            "function storyFrame(selected){var frames=selected.story&&selected.story.textFrames,m=[],i,f,r;if(!frames||typeof frames.length!==\"number\"||!frames.length)fail(\"text-range-source-unavailable\");for(i=0;i<frames.length;i++){f=frames[i];r=f.textRange;if(f.typename===\"TextFrame\"&&r&&selected.start>=r.start&&selected.end<=r.start+String(f.contents).length)m.push(f);}if(m.length===1)return m[0];if(frames.length===1&&frames[0].typename===\"TextFrame\")return frames[0];fail(\"threaded-text-not-supported\");}" +
            "function resolve(doc,uuid){var frame;if(!uuid)fail(\"source-uuid-unavailable\");if(typeof doc.getPageItemFromUuid!==\"function\")fail(\"uuid-lookup-unavailable\");frame=doc.getPageItemFromUuid(uuid);if(!frame)fail(\"source-uuid-not-found\");return frame;}" +
            "if(!app.documents.length)fail(\"there is no document\");var expected=decodeURIComponent(\"" + encoded(expectedText) + "\"),cached=decodeURIComponent(\"" + encoded(cachedNote) + "\"),next=decodeURIComponent(\"" + encoded(nextNote) + "\"),documentPath=decodeURIComponent(\"" + encoded(identity.documentPath || "") + "\"),uuid=decodeURIComponent(\"" + encoded(identity.uuid || "") + "\"),doc=app.activeDocument,frame;" +
            "if(!documentPath)fail(\"origin-document-identity-unavailable\");if(!doc.fullName||!doc.fullName.fsName||String(doc.fullName.fsName)!==documentPath)fail(\"origin-document-mismatch\");frame=resolve(doc,uuid);" +
            "if(frame.orientation!==TextOrientation.HORIZONTAL)fail(\"text-frame-vertical-unsupported\");if(frame.kind!==TextType.AREATEXT&&frame.kind!==TextType.POINTTEXT)fail(\"text-frame-kind-unsupported\");if(String(frame.contents)!==expected)fail(\"source-snapshot-mismatch\");if(String(frame.note)!==cached)fail(\"source-note-target-mismatch\");frame.note=next;if(String(frame.note)!==next)fail(\"store-readback-mismatch\");return \"B-bridge-talk:success\";}());";
    }
    function bridge(expectedText, cachedNote, nextNote, identity, callbacks, bridgeTalkRef) {
        var bt, sent, finished=false;
        if(!bridgeTalkRef) throw Error("B-bridge-talk-unavailable");
        if(typeof bridgeTalkRef.getSpecifier!=="function") throw Error("B-bridge-talk-specifier-unavailable");
        bt=new bridgeTalkRef(); bt.target=bridgeTalkRef.getSpecifier("illustrator"); if(!bt.target) throw Error("B-bridge-talk-target-unavailable"); bt.body=bridgeBody(expectedText,cachedNote,nextNote,identity); bt.timeout=30;
        function finish(callback,value){if(finished)return;finished=true;removeMessage(bt);callback(value);}
        bt.onResult=function(result){if(result&&result.body==="B-bridge-talk:success")finish(callbacks.success,{strategy:"B-bridge-talk",note:nextNote});else finish(callbacks.failure,"B-bridge-talk: invalid-result:"+(result&&result.body?result.body:"empty"));};
        bt.onError=function(result){finish(callbacks.failure,"B-bridge-talk: "+errorText(result&&result.body?result.body:result));};
        bt.onTimeout=function(result){finish(callbacks.failure,"B-bridge-talk: timeout:"+errorText(result&&result.body?result.body:result));};
        activeMessages.push(bt); try { sent=bt.send(); } catch(error) { removeMessage(bt); throw error; }
        callbacks.pending(sent===false?"B-bridge-talk: send=false (queued-or-not-sent)":"B-bridge-talk: send=true"); return bt;
    }
    function scriptLiteral(value) {
        var key, parts;
        if (value === null || value === undefined) return "null";
        if (typeof value === "string") return '"' + value.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\r/g,"\\r").replace(/\n/g,"\\n") + '"';
        if (typeof value === "number" || typeof value === "boolean") return String(value);
        if (value instanceof Array) { parts=[]; for (var i=0;i<value.length;i++) parts.push(scriptLiteral(value[i])); return "["+parts.join(",")+"]"; }
        parts=[]; for (key in value) if (value.hasOwnProperty(key)) parts.push(scriptLiteral(key)+":"+scriptLiteral(value[key])); return "{"+parts.join(",")+"}";
    }
    function renderedBridgeBody(expectedText, cachedNote, nextNote, renderFailureNote, identity, bundle, specifications, sources, stagePath, requestId) {
        if (renderFailureNote && typeof renderFailureNote === "object") {
            stagePath = sources; sources = specifications; specifications = bundle; bundle = identity; identity = renderFailureNote; renderFailureNote = nextNote;
        }
        var bundleLiteral=scriptLiteral(bundle), step1Path=encoded(sources.step1), segmentsPath=encoded(sources.segments), orchestrationPath=encoded(sources.orchestration), appearancePath=encoded(sources.appearance), multiPath=encoded(sources.multi), multiStorePath=encoded(sources.multiStore), projectionPath=encoded(sources.projection), multiRendererPath=encoded(sources.multiRenderer), nativeRendererPath=encoded(sources.nativeRenderer), renderSpecPath=encoded(sources.renderSpec), nativePath=encoded(sources.nativeCore), nativeStorePath=encoded(sources.nativeStore), nativeNoteAdapterPath=encoded(sources.nativeNoteAdapter), nativePersistencePath=encoded(sources.nativePersistence), nativeCoordinatorPath=encoded(sources.nativeCoordinator), nativeIdentityPath=encoded(sources.nativeIdentity), nativeBackendPath=encoded(sources.nativeBackend), nativeHostPath=encoded(sources.nativeHost), nativeIntegrationPath=encoded(sources.nativeIntegration), nativeRecoveryPath=encoded(sources.nativeRecovery), nativeRecoveryRuntimePath=encoded(sources.nativeRecoveryRuntime), adapterPath=encoded(sources.adapter), stagePathLiteral=encoded(stagePath || ""), documentPath=encoded(identity.documentPath || ""), uuid=encoded(identity.uuid || "");
        return "(function(){"+
            "var stageFilePath=decodeURIComponent(\""+stagePathLiteral+"\");function stage(s,d){var f,line;try{if(!stageFilePath)return;f=File(stageFilePath);if(!f.open(\"a\"))return;line=\"formal-multi-stage:v1;request=\"+encodeURIComponent(\""+encoded(requestId || "")+"\")+\";stage=\"+encodeURIComponent(String(s))+\";detail=\"+encodeURIComponent(String(d==null?\"\":d))+\"\\n\";f.write(line);f.close();}catch(ignore){try{if(f)f.close();}catch(ignoreClose){}}}function renderFailureResult(s,d,n){stage(s,d);return \"B-render-persist:render-failed:\"+s+\":\"+encodeURIComponent(String(d==null?\"\":d))+\":\"+encodeURIComponent(String(n==null?\"\":n));}function lifecycleFailure(s,d,n){stage(s,d);return \"B-render-persist:failure:\"+s+\":\"+encodeURIComponent(String(d==null?\"\":d))+\":\"+encodeURIComponent(String(n==null?\"\":n));}function terminalBundleNote(base,plan,activated,reason){var result=FormalMulti.clone(bundle),i,j,o,p,eligible;result.renderStatus=activated?\"complete\":\"failed\";for(i=0;i<result.occurrences.length;i++){o=result.occurrences[i];eligible=o.enabled&&!o.unsupported&&o.readingConfirmed&&o.reading;o.renderStatus=\"pending\";o.renderReasons=[];o.renderBoundaries=[];o.renderUnresolvedBoundaries=[];for(j=0;j<(plan.plans||[]).length;j++){p=plan.plans[j];if(p.occurrenceId===o.occurrenceId&&eligible&&p.status===\"complete\"&&!p.suppressed){o.renderStatus=activated?\"complete\":\"failed\";o.renderReasons=activated?[]:[String(reason)];}}}return FormalMultiStore.write(base,result);}function fail(m){stage(\"bridge\",m);throw Error(m);} "+
            "$.evalFile(File(decodeURIComponent(\""+step1Path+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+segmentsPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+orchestrationPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+appearancePath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+multiPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+multiStorePath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+projectionPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+multiRendererPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeRendererPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+renderSpecPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativePath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeStorePath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeNoteAdapterPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativePersistencePath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeCoordinatorPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeIdentityPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeBackendPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeHostPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeIntegrationPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeRecoveryPath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+nativeRecoveryRuntimePath+"\")));"+
            "$.evalFile(File(decodeURIComponent(\""+adapterPath+"\")));"+
            "if(typeof FormalStep1===\"undefined\"||typeof FormalSegments===\"undefined\"||typeof FormalMultiOrchestration===\"undefined\"||typeof FormalMultiRenderer===\"undefined\"||typeof FormalMulti===\"undefined\"||typeof FormalMultiStore===\"undefined\"||typeof FormalMultiProjection===\"undefined\"||typeof FormalMultiNativeRenderer===\"undefined\"||typeof FormalAreaTextRenderSpec===\"undefined\"||typeof FormalAreaTextNative===\"undefined\"||typeof FormalAreaTextNativePersistenceFacade===\"undefined\"||typeof FormalAreaTextNativeTransactionCoordinator===\"undefined\"||typeof FormalAreaTextNativeIntegration===\"undefined\"||typeof FormalAreaTextNativeRecovery===\"undefined\"||typeof FormalAreaTextNativeRecoveryRuntime===\"undefined\"||typeof FormalAreaTextNativeHost===\"undefined\"||typeof FormalStep2Adapter===\"undefined\")fail(\"runtime-symbol-missing\");"+
            "var expected=decodeURIComponent(\""+encoded(expectedText)+"\"),cached=decodeURIComponent(\""+encoded(cachedNote)+"\"),next=decodeURIComponent(\""+encoded(nextNote)+"\"),renderFailure=decodeURIComponent(\""+encoded(renderFailureNote)+"\"),documentPath=decodeURIComponent(\""+documentPath+"\"),uuid=decodeURIComponent(\""+uuid+"\"),bundle="+bundleLiteral+",doc,frame,renderAdapter,observation,plan,failurePlan,failureDetail,failureBundle,expectedFailureNote,finalNote,nativePlan,nativeOrchestration,previousManifest,transition,seam,transaction,prepared,verified,sourceFontName,retireResult,retireId,retireResolution,activated=false,cleanupEvidence,i,j;function staleEvidenceFailure(reason){var failed=FormalMulti.clone(bundle),k,o;failed.renderStatus=\"failed\";for(k=0;k<failed.occurrences.length;k++){o=failed.occurrences[k];o.renderStatus=o.enabled&&!o.unsupported&&o.readingConfirmed&&o.reading?\"failed\":\"pending\";o.renderReasons=o.renderStatus===\"failed\"?[String(reason)]:[];o.renderBoundaries=[];o.renderUnresolvedBoundaries=[];}return FormalMultiStore.write(cached,failed);}"+
            "function recoverNative(note,providedAction){var state=FormalAreaTextNativePersistenceFacade.read(frame).manifest,action=providedAction,ids,result,i,resolution;function all(a,b){var out=[],j;for(j=0;j<a.length;j++)out.push(a[j]);for(j=0;j<b.length;j++)out.push(b[j]);return out;}function remove(values){for(i=0;i<values.length;i++){resolution=FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames,bundle.sourceFrameId,values[i]);if(resolution.status===\"duplicate\")fail(\"native-recovery-duplicate-candidate\");if(resolution.status===\"found\")resolution.frame.remove();}}if(!state&&!action)return note;action=action||FormalAreaTextNativeRecovery.restart(state,bundle.sourceFrameId,function(sourceId,physicalId){return FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames,sourceId,physicalId);});ids=all(action.found||[],action.missing||[]);if(action.action===\"prepare-candidates\"||action.action===\"reverify-candidates\"){remove(action.found||[]);result=FormalAreaTextNativeTransactionCoordinator.abort(frame,expected,String(note),action.requestId,ids);result=FormalAreaTextNativeTransactionCoordinator.cleanupDiscarded(frame,expected,String(result.note),ids);return result.note;}if(action.action===\"cleanup-discarded\"){remove(action.found||[]);result=FormalAreaTextNativeTransactionCoordinator.cleanupDiscarded(frame,expected,String(note),ids);return result.note;}if(action.action===\"cleanup-retirement\"){remove(action.found||[]);result=FormalAreaTextNativeTransactionCoordinator.retire(frame,expected,String(note),ids);return result.note;}if(action.action===\"finish-operation\"){result=FormalAreaTextNativeTransactionCoordinator.finish(frame,expected,String(note),action.requestId);return result.note;}if(action.action===\"idle\")return note;fail(\"native-recovery-manual-required:\"+action.action);}"+
            "function renderFailureResult(s,d,n){var note=n;if(s===\"observation\"||(s===\"plan\"&&String(d).indexOf(\"|\")<0)){note=staleEvidenceFailure(String(d));frame.note=note;if(String(frame.note)!==note)fail(\"persistence-after-render-failure-mismatch\");}stage(s,d);return \"B-render-persist:render-failed:\"+s+\":\"+encodeURIComponent(String(d==null?\"\":d))+\":\"+encodeURIComponent(String(note==null?\"\":note));}"+
            "if(!app.documents.length)fail(\"there is no document\");doc=app.activeDocument;if(!documentPath||!doc.fullName||!doc.fullName.fsName||String(doc.fullName.fsName)!==documentPath)fail(\"origin-document-mismatch\");if(!uuid||typeof doc.getPageItemFromUuid!==\"function\")fail(\"uuid-lookup-unavailable\");frame=doc.getPageItemFromUuid(uuid);if(!frame)fail(\"source-uuid-not-found\");if(String(frame.contents)!==expected)fail(\"source-snapshot-mismatch\");if(String(frame.note)!==cached)fail(\"source-note-target-mismatch\");stage(\"bridge\",\"validated\");cached=(function(note){var snapshot=FormalAreaTextNativePersistenceFacade.read(frame),result;if(!snapshot.manifest)return note;result=FormalAreaTextNativeRecoveryRuntime.converge(snapshot.manifest,bundle.sourceFrameId,function(sourceId,physicalId){return FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames,sourceId,physicalId);},function(action){stage(\"native.recovery\",action.action+\"|request=\"+(action.requestId||\"\")+\"|found=\"+(action.found||[]).length+\"|missing=\"+(action.missing||[]).length);note=recoverNative(note,action);return FormalAreaTextNativePersistenceFacade.read(frame).manifest;},function(action){stage(\"native.recovery\",\"report:\"+action.action);},8);stage(\"native.recovery\",\"terminal|steps=\"+result.steps);return FormalAreaTextNativePersistenceFacade.read(frame).note;}(cached));next=FormalMultiStore.write(cached,bundle);renderFailure=FormalMultiStore.write(cached,FormalMultiStore.read(renderFailure)||bundle);frame.note=cached;if(String(frame.note)!==cached)fail(\"native-recovery-readback-mismatch\");renderAdapter=FormalStep2Adapter(doc,frame);try{observation=renderAdapter.observe();}catch(observationError){frame.note=renderFailure;if(String(frame.note)!==renderFailure)fail(\"persistence-after-render-failure-mismatch\");return renderFailureResult(\"observation\",observationError.message||observationError,String(frame.note));}stage(\"observation\",observation.status,(observation.reasons||[]).join(\"|\"));"+
            "if(observation.status!==\"complete\"){frame.note=renderFailure;if(String(frame.note)!==renderFailure)fail(\"persistence-after-render-failure-mismatch\");return renderFailureResult(\"observation\",observation.reasons||observation.status,String(frame.note));}"+
            "try{plan=FormalMultiRenderer.plan(bundle,expected,observation);}catch(planError){frame.note=renderFailure;if(String(frame.note)!==renderFailure)fail(\"persistence-after-render-failure-mismatch\");return renderFailureResult(\"plan\",planError.message||planError,String(frame.note));}stage(\"plan\",plan.status,(plan.plans&&plan.plans.length)||0);if(plan.status!==\"complete\"){failurePlan=plan.plans&&plan.plans.length?plan.plans[plan.plans.length-1]:null;failureDetail=failurePlan?(failurePlan.annotationId+\"|\"+(failurePlan.occurrenceId||\"\")+\"|\"+failurePlan.status+\"|\"+(failurePlan.reasons||[]).join(\",\")+\"|\"+(failurePlan.boundaries||[]).join(\",\")+\"|\"+(failurePlan.unresolvedBoundaries||[]).join(\",\")):plan.status;if(failurePlan){failureBundle=FormalMulti.clone(bundle);failureBundle.renderStatus=plan.status===\"failed\"?\"failed\":\"unresolved\";for(i=0;i<failureBundle.occurrences.length;i++){failureBundle.occurrences[i].renderStatus=\"pending\";failureBundle.occurrences[i].renderReasons=[];failureBundle.occurrences[i].renderBoundaries=[];failureBundle.occurrences[i].renderUnresolvedBoundaries=[];}for(i=0;i<plan.plans.length;i++)for(j=0;j<failureBundle.occurrences.length;j++)if(plan.plans[i].occurrenceId===failureBundle.occurrences[j].occurrenceId){failureBundle.occurrences[j].renderStatus=plan.plans[i].status;failureBundle.occurrences[j].renderReasons=(plan.plans[i].reasons||[]);failureBundle.occurrences[j].renderBoundaries=(plan.plans[i].boundaries||[]);failureBundle.occurrences[j].renderUnresolvedBoundaries=(plan.plans[i].unresolvedBoundaries||[]);}expectedFailureNote=FormalMultiStore.write(cached,failureBundle);frame.note=expectedFailureNote;if(String(frame.note)!==expectedFailureNote)fail(\"persistence-after-render-failure-mismatch\");}else{frame.note=renderFailure;if(String(frame.note)!==renderFailure)fail(\"persistence-after-render-failure-mismatch\");}return renderFailureResult(\"plan\",failureDetail,String(frame.note));}"+
            "try{nativeOrchestration={planAll:function(){return {status:plan.status,results:plan.plans};}};sourceFontName=\"\";try{sourceFontName=String(frame.textRange.characterAttributes.textFont.name);}catch(fontError){}previousManifest=FormalAreaTextNativePersistenceFacade.read(frame).manifest;nativePlan=FormalMultiNativeRenderer.createSpecs(bundle,{status:plan.status,results:plan.plans},\""+encoded(requestId || "")+"\",sourceFontName,previousManifest);if(nativePlan.status!==\"complete\")fail(\"native-render-plan-incomplete\");frame.note=next;if(String(frame.note)!==next)fail(\"store-readback-mismatch\");transition=FormalMultiNativeRenderer.transition(previousManifest,nativePlan.desiredLogicalSegmentIds,nativePlan.specs);transaction={source:frame,requestId:\""+encoded(requestId || "")+"\",expectedContents:expected,expectedNote:next};seam=FormalAreaTextNativeIntegration.create(nativeOrchestration,FormalAreaTextNativeHost(doc,frame.layer),FormalAreaTextNativeTransactionCoordinator);prepared=seam.planAndPrepare(bundle,expected,observation,nativePlan.specs,transaction);verified=seam.verify(prepared);seam.activate(frame,expected,String(frame.note),\""+encoded(requestId || "")+"\",verified,transition.retiredPhysicalIds,[],transition.removedLogicalSegmentIds);activated=true;for(i=0;i<transition.retiredPhysicalIds.length;i++){retireId=transition.retiredPhysicalIds[i];retireResolution=FormalAreaTextNativeOutputIdentity.resolve(doc.textFrames,bundle.sourceFrameId,retireId);if(retireResolution.status===\"found\")retireResolution.frame.remove();else if(retireResolution.status===\"duplicate\")fail(\"native-retire-duplicate\");}retireResult=FormalAreaTextNativeTransactionCoordinator.retire(frame,expected,String(frame.note),transition.retiredPhysicalIds);FormalAreaTextNativeTransactionCoordinator.finish(frame,expected,String(retireResult.note),\""+encoded(requestId || "")+"\");finalNote=terminalBundleNote(String(frame.note),plan,true,\"\");frame.note=finalNote;if(String(frame.note)!==finalNote)fail(\"persistence-after-render-success-mismatch\");stage(\"native\",\"success\",\"finish\");return \"B-render-persist:success:\"+encodeURIComponent(String(frame.note));}catch(nativeError){cleanupEvidence=nativeError.cleanupPendingIds||[];if(!activated&&seam&&prepared){try{seam.abort(prepared,nativeError);}catch(abortError){cleanupEvidence=cleanupEvidence.concat(abortError.cleanupPendingIds||[]);stage(\"native.abort\",abortError.message||abortError);}}finalNote=terminalBundleNote(String(frame.note),plan,activated,(nativeError.message||nativeError)+\";cleanupPending=\"+cleanupEvidence.join(\",\"));frame.note=finalNote;if(String(frame.note)!==finalNote)fail(\"persistence-after-render-failure-mismatch\");return lifecycleFailure(\"native\",(nativeError.message||nativeError)+\";cleanupPending=\"+cleanupEvidence.join(\",\"),String(frame.note));}}());";
    }
    function parseRenderDetail(detail) { var p=String(detail||"").split("|"), values=[], i, item; if(p.length<6) return []; for(i=0;i<3;i++) values.push(p[i]); item={annotationId:p[0],occurrenceId:p[1],status:p[2],reasons:p[3]?p[3].split(","):[],boundaries:[],unresolvedBoundaries:[]}; if(p[4]) for(i=0;i<p[4].split(",").length;i++) item.boundaries.push(Number(p[4].split(",")[i])); if(p[5]) for(i=0;i<p[5].split(",").length;i++) item.unresolvedBoundaries.push(Number(p[5].split(",")[i])); values=[]; values.push(item); return values; }
    function renderedBridge(expectedText, cachedNote, nextNote, renderFailureNote, identity, bundle, specifications, sources, callbacks, bridgeTalkRef, stagePath, requestId) {
        var bt, sent, finished=false;
        if(!bridgeTalkRef) throw Error("B-bridge-talk-unavailable");
        if(typeof bridgeTalkRef.getSpecifier!=="function") throw Error("B-bridge-talk-specifier-unavailable");
        if (stagePath) verifyStagePath(stagePath, requestId || "unknown");
        verifyRuntimeSources(sources);
        bt=new bridgeTalkRef(); bt.target=bridgeTalkRef.getSpecifier("illustrator"); if(!bt.target) throw Error("B-bridge-talk-target-unavailable"); bt.body=renderedBridgeBody(expectedText,cachedNote,nextNote,renderFailureNote,identity,bundle,specifications,sources,stagePath,requestId); bt.timeout=30;
        function finish(callback,value){if(finished)return;finished=true;removeMessage(bt);callback(value);}
        bt.onResult=function(result){var body=result&&result.body?String(result.body):"",prefix="B-render-persist:success:",renderPrefix="B-render-persist:render-failed:",failurePrefix="B-render-persist:failure:",detail,persistedNote,parts;if(body.substring(0,prefix.length)===prefix)finish(callbacks.success,{strategy:"B-render-persist",note:decodeURIComponent(body.substring(prefix.length)),noteVerified:true,renderStatus:"complete"});else if(body.substring(0,renderPrefix.length)===renderPrefix){parts=body.substring(renderPrefix.length).split(":");detail=parts[0]+(parts.length>1?":"+decodeURIComponent(parts[1]):"");persistedNote=parts.length>2?decodeURIComponent(parts[2]):null;finish(callbacks.success,{strategy:"B-render-persist",note:persistedNote,renderStatus:parts[0]==="plan"?"unresolved":"failed",renderResults:parts[0]==="plan"?parseRenderDetail(parts.length>1?decodeURIComponent(parts[1]):""):[],noteVerified:persistedNote!==null,reason:detail});}else if(body.substring(0,failurePrefix.length)===failurePrefix){parts=body.substring(failurePrefix.length).split(":");detail=parts[0]+(parts.length>1?":"+decodeURIComponent(parts[1]):"");persistedNote=parts.length>2?decodeURIComponent(parts.slice(2).join(":")):null;finish(callbacks.failure,{strategy:"B-render-persist",kind:parts[0],reason:detail,note:persistedNote,noteVerified:persistedNote!==null});}else if(body==="B-render-persist:persistence-failed")finish(callbacks.failure,"B-render-persist: persistence-failed");else finish(callbacks.failure,"B-render-persist: invalid-result:"+(body||"empty"));};
        bt.onError=function(result){finish(callbacks.failure,{strategy:"B-render-persist",kind:"transport-uncertain",reason:"bridge-error:"+errorText(result&&result.body?result.body:result),note:null,noteVerified:false,retrySafe:false});};
        bt.onTimeout=function(result){finish(callbacks.failure,{strategy:"B-render-persist",kind:"transport-uncertain",reason:"bridge-timeout:"+errorText(result&&result.body?result.body:result),note:null,noteVerified:false,retrySafe:false});};
        activeMessages.push(bt); try { sent=bt.send(); } catch(error) { removeMessage(bt); throw error; }
        callbacks.pending(sent===false?"B-render-persist: send=false (queued-or-not-sent)":"B-render-persist: send=true"); return bt;
    }
    function saveRendered(expectedText, cachedNote, bundle, identity, specifications, sources, callbacks, bridgeTalkRef, stagePath, requestId) {
        var nextNote=FormalMultiStore.write(cachedNote,bundle), renderFailureBundle={}, renderFailureNote, key, diagnostics=[], result;
        callbacks=callbacks||{};
        for (key in bundle) if (bundle.hasOwnProperty(key)) renderFailureBundle[key]=bundle[key];
        renderFailureBundle.renderStatus="failed";
        renderFailureNote=FormalMultiStore.write(cachedNote,renderFailureBundle);
        try {
            result=renderedBridge(expectedText,cachedNote,nextNote,renderFailureNote,identity||{},bundle,specifications,sources,{
                pending:function(message){diagnostics.push(message);if(callbacks.pending)callbacks.pending(diagnostics.slice(0));},
                success:function(value){value.diagnostics=diagnostics.concat([value.renderStatus&&value.renderStatus!=="complete"?"B-render-persist: transport-success / render-unresolved":"B-render-persist: success"]);if(callbacks.success)callbacks.success(value);},
                failure:function(message){var value=message;if(message&&typeof message==="object"){value.diagnostics=diagnostics.concat(["B-render-persist: "+(message.kind||"failure")+" / "+(message.reason||"")]);if(callbacks.failure)callbacks.failure(value);}else{diagnostics.push(message);if(callbacks.failure)callbacks.failure(diagnostics.slice(0));}}
            },bridgeTalkRef||(typeof BridgeTalk!=="undefined"?BridgeTalk:null),stagePath,requestId);
            return {status:"pending",strategy:"B-render-persist",note:nextNote,diagnostics:diagnostics,bridge:result};
        } catch(error) { diagnostics.push("B-render-persist: "+errorText(error)); return {status:"failed",diagnostics:diagnostics}; }
    }
    function save(source, cachedNote, bundle, identity, callbacks, bridgeTalkRef) {
        var nextNote=FormalMultiStore.write(cachedNote,bundle), diagnostics=[], result;
        callbacks=callbacks||{};
        try { source.note=nextNote; diagnostics.push("A-direct-source-note: success"); return {status:"success",strategy:"A-direct-source-note",note:nextNote,diagnostics:diagnostics}; }
        catch(error) { diagnostics.push("A-direct-source-note: "+errorText(error)); }
        try {
            result=bridge(bundle.textSnapshot,cachedNote,nextNote,identity||{},{pending:function(message){diagnostics.push(message);if(callbacks.pending)callbacks.pending(diagnostics.slice(0));},success:function(value){value.diagnostics=diagnostics.concat(["B-bridge-talk: success"]);if(callbacks.success)callbacks.success(value);},failure:function(message){diagnostics.push(message);if(callbacks.failure)callbacks.failure(diagnostics.slice(0));}},bridgeTalkRef||(typeof BridgeTalk!=="undefined"?BridgeTalk:null));
            return {status:"pending",strategy:"B-bridge-talk",note:nextNote,diagnostics:diagnostics,bridge:result};
        } catch(error) { diagnostics.push("B-bridge-talk: "+errorText(error)); return {status:"failed",diagnostics:diagnostics}; }
    }
    function saveBridgeOnly(expectedText, cachedNote, bundle, identity, callbacks, bridgeTalkRef) {
        var nextNote=FormalMultiStore.write(cachedNote,bundle), diagnostics=[], result;
        callbacks=callbacks||{};
        try {
            result=bridge(expectedText,cachedNote,nextNote,identity||{},{pending:function(message){diagnostics.push(message);if(callbacks.pending)callbacks.pending(diagnostics.slice(0));},success:function(value){value.diagnostics=diagnostics.concat(["B-bridge-talk: success"]);if(callbacks.success)callbacks.success(value);},failure:function(message){diagnostics.push(message);if(callbacks.failure)callbacks.failure(diagnostics.slice(0));}},bridgeTalkRef||(typeof BridgeTalk!=="undefined"?BridgeTalk:null));
            return {status:"pending",strategy:"B-bridge-talk",note:nextNote,diagnostics:diagnostics,bridge:result};
        } catch(error) { diagnostics.push("B-bridge-talk: "+errorText(error)); return {status:"failed",diagnostics:diagnostics}; }
    }
    return {save:save,saveBridgeOnly:saveBridgeOnly,saveRendered:saveRendered,bridgeBody:bridgeBody,renderedBridgeBody:renderedBridgeBody,captureIdentity:captureIdentity,verifyRuntimeSources:verifyRuntimeSources};
}());
if(typeof module!=="undefined")module.exports=FormalMultiPersistenceAdapter;
