/* Pure Gate C segment planning. No proportional reading split is inferred. */
var FormalSegments=(function(){
 function fail(m){throw Error(m);}
 function validateHints(hints,baseLength,readingLength){var lastBase=0,lastReading=0,i,h;if(!(hints instanceof Array))fail("hints-not-array");for(i=0;i<hints.length;i++){h=hints[i];if(!h||typeof h.baseBoundaryAfter!=="number"||!isFinite(h.baseBoundaryAfter)||typeof h.readingBoundaryAfter!=="number"||!isFinite(h.readingBoundaryAfter)||h.baseBoundaryAfter<=lastBase||h.baseBoundaryAfter>=baseLength||h.readingBoundaryAfter<=lastReading||h.readingBoundaryAfter>=readingLength||typeof h.baseText!=="string"||typeof h.reading!=="string")fail("invalid-split-hint");lastBase=h.baseBoundaryAfter;lastReading=h.readingBoundaryAfter;}return hints;}
 function segments(base,reading,hints){validateHints(hints,base.length,reading.length);var out=[],bs=0,rs=0,i,h;for(i=0;i<=hints.length;i++){h=hints[i];var be=h?h.baseBoundaryAfter:base.length,re=h?h.readingBoundaryAfter:reading.length;out.push({baseText:base.substring(bs,be),reading:reading.substring(rs,re),renderSegmentId:"segment-"+(i+1)});bs=be;rs=re;}return out;}
 function plan(base,reading,lines,hints,baseRevision,readingRevision){if(!lines||!lines.length)return{status:"unresolved",reasons:["line-map-unavailable"]};if(lines.length===1){var one=segments(base,reading,[]);one[0].geometry=lines[0].geometry;return{status:"complete",segments:one,ignoredHints:true};}var boundaries=[],i,j,matched,usable=[],unresolved=[];for(i=0;i<lines.length-1;i++)boundaries.push(lines[i].end);if(!hints||!hints.length)return{status:"unresolved",reasons:["split-hint-required"],boundaries:boundaries,unresolvedBoundaries:boundaries};validateHints(hints,base.length,reading.length);for(i=0;i<hints.length;i++)if(hints[i].baseText!==base||hints[i].reading!==reading)return{status:"unresolved",reasons:["split-hint-stale"]};for(i=0;i<boundaries.length;i++){matched=null;for(j=0;j<hints.length;j++)if(hints[j].baseBoundaryAfter===boundaries[i]){matched=hints[j];break;}if(matched)usable.push(matched);else unresolved.push(boundaries[i]);}if(unresolved.length)return{status:"unresolved",reasons:["split-hint-boundary-mismatch"],boundaries:boundaries,reusableHints:usable,unresolvedBoundaries:unresolved};var out=segments(base,reading,usable);for(i=0;i<out.length;i++)out[i].geometry=lines[i].geometry;return{status:"complete",segments:out,reusableHints:usable};}
 return{validateHints:validateHints,segments:segments,plan:plan};
}());
if(typeof module!=="undefined")module.exports=FormalSegments;
