/* Pure Gate C segment planning. No proportional reading split is inferred. */
var FormalSegments=(function(){
 function fail(m){throw Error(m);}
 function validateHints(hints,baseLength,readingLength){var last=0,i,h;if(!(hints instanceof Array))fail("hints-not-array");for(i=0;i<hints.length;i++){h=hints[i];if(!h||h.baseBoundaryAfter<=last||h.baseBoundaryAfter>=baseLength||h.readingBoundaryAfter<=0||h.readingBoundaryAfter>=readingLength||!isFinite(h.baseRevision)||!isFinite(h.readingRevision))fail("invalid-split-hint");last=h.baseBoundaryAfter;}return hints;}
 function segments(base,reading,hints){validateHints(hints,base.length,reading.length);var out=[],bs=0,rs=0,i,h;for(i=0;i<=hints.length;i++){h=hints[i];var be=h?h.baseBoundaryAfter:base.length,re=h?h.readingBoundaryAfter:reading.length;out.push({baseText:base.substring(bs,be),reading:reading.substring(rs,re),renderSegmentId:"segment-"+(i+1)});bs=be;rs=re;}return out;}
 function plan(base,reading,lines,hints,baseRevision,readingRevision){if(!lines||!lines.length)return{status:"unresolved",reasons:["line-map-unavailable"]};if(lines.length===1)return{status:"complete",segments:segments(base,reading,[]),ignoredHints:true};var boundaries=[],i;for(i=0;i<lines.length-1;i++)boundaries.push(lines[i].end);if(!hints||!hints.length)return{status:"unresolved",reasons:["split-hint-required"],boundaries:boundaries};validateHints(hints,base.length,reading.length);for(i=0;i<hints.length;i++)if(hints[i].baseRevision!==baseRevision||hints[i].readingRevision!==readingRevision)return{status:"unresolved",reasons:["split-hint-stale"]};if(hints.length!==boundaries.length)return{status:"unresolved",reasons:["split-hint-boundary-mismatch"]};for(i=0;i<boundaries.length;i++)if(hints[i].baseBoundaryAfter!==boundaries[i])return{status:"unresolved",reasons:["split-hint-boundary-mismatch"]};return{status:"complete",segments:segments(base,reading,hints)};}
 return{validateHints:validateHints,segments:segments,plan:plan};
}());
if(typeof module!=="undefined")module.exports=FormalSegments;
